### PR TITLE
Manual fee rate support

### LINKED ISSUE #538: [bug] Fee estimation creates negative output value
### Background

tapcli assets send --addr taptb1qqqsqq3q3nk6vdurca4n023c87adydh78vdx9y3ws6vqlfmtr6mcg5454ptqgggzqrczxmug0nx4st9eh9mnr8lz3uetjkxge34varschl96van0vhtsvggrmktx286tl3yp97k0fhyskr0rzdeu7jhsa3pdectudce5e0cvahhqsqgvkakfyz

### Error on lnd daemon
023-10-02 03:06:47.811 [INF] BTCN: Attempting to fetch set of un-checkpointed filters at height=2515625, hash=0000000000002ffaf601d41448448e7f90ae991960dd8d13a36a1cfa4963175b
2023-10-02 03:06:48.132 [INF] NTFN: New block: height=2515624, sha=00000000000022c30801dbf4693a5ce1aab29df02769ef2696a688b8e535b6cb
2023-10-02 03:06:48.132 [INF] UTXN: Attempting to graduate height=2515624: num_kids=0, num_babies=0
2023-10-02 03:06:52.812 [WRN] BTCN: All peers rejected transaction 204af7dd16b2d4b1a9c54cef9e3d488c2302b5a282c56c192350236ebe27cd25 checking errors
2023-10-02 03:06:52.812 [ERR] BTCN: Unable to rebroadcast transaction 204af7dd16b2d4b1a9c54cef9e3d488c2302b5a282c56c192350236ebe27cd25: rejected by 15.204.85.140:18333: transaction output has negative value of -259

### Your environment
testnet 
image: polarlightning/tapd:0.2.3-alpha

On LND Damemon : lncli --network=testnet walletbalance 
{
    "total_balance": "36641",
    "confirmed_balance": "34900",
    "unconfirmed_balance": "1741",
    "locked_balance": "0",
    "reserved_balance_anchor_chan": "0",
    "account_balance": {
        "default": {
            "confirmed_balance": "33900",
            "unconfirmed_balance": "-259"
        },
        "imported": {
            "confirmed_balance": "1000",
            "unconfirmed_balance": "2000"
        }
    }
}

### Problems
send faild.
Is there any problems on using of uxto?

### LINKED ISSUE #587: [bug]: Onchain fees set to 1 sat/byte on main net with neutrino
### Background

I am trying to run tapd with neutrino.

When minting a currency the minting transaction is submitted with 1sat / vbyte fees

### Your environment

```
$ tapcli --network=mainnet getinfo
{
    "version": "0.3.0-alpha.rc2 commit=v0.3.0-alpha.rc2",
    "lnd_version": "0.17.0-beta",
    "network": "mainnet"
}
```

```
$uname -mrsv  
Linux 6.1.55-75.123.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Sep 26 20:06:16 UTC 2023 x86_64
```

* any other relevant environment details
I am running and with neutrino

### Steps to reproduce

Start LND
```
lnd --bitcoin.mainnet --debuglevel=debug --bitcoin.node=neutrino --neutrino.addpeer=faucet.lightning.community --neutrino.addpeer=btcd-testnet.lightning.computer --neutrino.addpeer=testnet3-btcd.zaphq.io --neutrino.addpeer=btcd0.lightning.computer:18333 --neutrino.addpeer=lnd.bitrefill.com:18333 --neutrino.addpeer=testnet1-btcd.zaphq.io --neutrino.addpeer=testnet2-btcd.zaphq.io --neutrino.addpeer=neutrino.addpeer=testnet4-btcd.zaphq.io --rpclisten=0.0.0.0:10009  --feeurl=https://nodes.lightning.computer/fees/v1/btc-fee-estimates.json
```

Start TAPD
```
tapd --network=mainnet --debuglevel=debug --lnd.host=localhost:10009 --lnd.macaroonpath=/home/ec2-user/.lnd/data/chain/bitcoin/mainnet/admin.macaroon --lnd.tlspath=/home/ec2-user/.lnd/tls.cert --rpclisten=0.0.0.0:10029 --restlisten=0.0.0.0:8089 --batch-minting-interval="1s"
```

Submit minting transaction
```
$ tapcli assets mint --type=normal --name=ShitcoinOpps2 --supply=1000000 --meta_bytes="test metadata" --enable_emission=false
$ tapcli assets mint finalize
```

See the submitted transaction details
```
$lncli listchaintxns
```
....shows 1 sat / vbyte fees....

### Expected behavior

I would like the fees to be set higher to be able to mind in one block .

### Actual behavior

Fees are set to 1 sat / vbyte

### PR DESCRIPTION
**Pull request by jharveyb**
Fixes #587
Fixes #538

Updates the planter and freighter to accept a fee rate in sat/kw, the same unit as the fee estimator, to use for the anchor transaction. The fee rate is checked against a minimum but not maximum, so users should be careful with fee units to avoid accidental overpayment.

### CODE REVIEW

File: tapgarden/caretaker.go [hunk 1]
```diff
@@ -30,8 +31,10 @@ import (
 var (
 	// GenesisDummyScript is a dummy script that we'll use to fund the
 	// initial PSBT packet that'll create initial set of assets. It's the
-	// same size as a encoded P2TR output.
-	GenesisDummyScript [34]byte
+	// same size as a encoded P2TR output and has a valid P2TR prefix.
+	GenesisDummyScript = append(
+		[]byte{0x51, 0x20}, bytes.Repeat([]byte{0x00}, 32)...,
```
Comment (Roasbeef) [inline tapgarden/caretaker.go:37]: Ah issue was it wasn't being recognized as proper P2TR before? Then possilby fell through to some default I guess. 

I think we can make this a bit more readable as: 
```go
GenesisDummyScript []byte{txscript.OP_1, ...}
```

Or we could even make a custom script builder, but `OP_1` makes it a bit easier to parse imo.

Comment (Roasbeef) [reply tapgarden/caretaker.go:37]: > Then possilby fell through to some default I guess.

If this is the case, can we add to the commit message?

File: tapscript/send.go [hunk 2]
```diff
@@ -105,10 +106,13 @@ var (
...
 func createDummyOutput() *wire.TxOut {
-	// The dummy PkScript is the same size as an encoded P2TR output.
+	// The dummy PkScript is the same size as an encoded P2TR output and has
+	// a valid P2TR prefix.
 	newOutput := wire.TxOut{
-		Value:    int64(DummyAmtSats),
-		PkScript: make([]byte, 34),
+		Value: int64(DummyAmtSats),
+		PkScript: append(
+			[]byte{0x51, 0x20}, bytes.Repeat([]byte{0x00}, 32)...,
```
Comment (Roasbeef) [inline tapscript/send.go:114]: Maybe move `GenesisDummyScript` into this package so it can be reused?

File: tapgarden/planter.go [hunk 3]
```diff
@@ -485,7 +494,7 @@ func (c *ChainPlanter) gardener() {
 				continue
 			}
 
-			_, err := c.finalizeBatch()
+			_, err := c.finalizeBatch(nil)
```
Comment (Roasbeef) [inline tapgarden/planter.go:497]: This path only gets hit in tests right?

File: tapfreighter/chain_porter.go [hunk 4]
```diff
@@ -880,14 +881,32 @@ func (p *ChainPorter) stateStep(currentPkg sendPackage) (*sendPackage, error) {
...
+		// First, use a manual fee rate if specified by the parcel.
+		// TODO(jhb): Support PSBT flow / PreSignedParcels
+		addrParcel, ok := currentPkg.Parcel.(*AddressParcel)
+		switch {
+		case ok && addrParcel.transferFeeRate != nil:
+			feeRate = *addrParcel.transferFeeRate
+			log.Infof("sending with manual fee rate")
+
+		default:
+			feeRate, err = p.cfg.ChainBridge.EstimateFee(
```
Comment (Roasbeef) [inline tapfreighter/chain_porter.go:898]: Rather than conditionally call estimation here, we could instead lift it up to the rpcserver. So then we can drop the pointer to fee rate, as we compute that head of time.

File: tapgarden/caretaker.go (hunk 1 above)
Comment (Roasbeef) [reply tapgarden/caretaker.go:37]: An example of the builder route: https://github.com/lightningnetwork/lnd/blob/master/input/taproot.go#L144-L149C25

Comment (jharveyb) [reply tapgarden/caretaker.go:37]: Yeah I think it was just misclassified but Oli found the alt script type, I don't recall it exactly. Will add notes to commit msg tho.

File: tapscript/send.go (hunk 2 above)
Comment (jharveyb) [reply tapscript/send.go:114]: Will just move to `asset`.

File: tapgarden/planter.go (hunk 3 above)
Comment (jharveyb) [reply tapgarden/planter.go:497]: I didn't see exactly where the ticker was turned off currently.

File: rpcserver.go [hunk 5]
```diff
@@ -443,12 +444,39 @@ func (r *rpcServer) MintAsset(ctx context.Context,
...
 
+// checkFeeRateSanity ensures that the provided fee rate is above the same
+// minimum fee used as a floor in the fee estimator.
+func checkFeeRateSanity(rpcFeeRate uint32) (*chainfee.SatPerKWeight, error) {
+	var feeRate *chainfee.SatPerKWeight
+	switch {
+	case rpcFeeRate == 0:
+		// No manual fee rate was set, which is the default.
+
+	case rpcFeeRate <= uint32(chainfee.FeePerKwFloor):
```
Comment (Roasbeef) [inline rpcserver.go:455]: I think we want to allow the fee floor? Which ends up being 1 sat/byte or so.

**Review by Roasbeef — APPROVED** [review]
LGTM 🦚

**Comment by Liongrass** [comment]
In line with our other software, this flag could be called `--sat_per_vbyte` and be measured in sat/vB. We use the term `fee_rate` a bit differently in LND.

**Comment by jharveyb** [comment]
Good point, will add that change in the upcoming fee PR.
