### PR TITLE
tapgarden: fix races and deadlocks in caretaker

### LINKED ISSUE #360: tapgarden: race in minting tests
From CI run of #358, where changes are unrelated.

```bash
panic: test timed out after 20m0s
running tests:
	TestBatchedAssetIssuance (19m49s)
	TestBatchedAssetIssuance/minting_with_cancellation (19m40s)

goroutine 1417 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:2241 +0x3c5
created by time.goFunc
	/opt/hostedtoolcache/go/1.20.4/x64/src/time/sleep.go:176 +0x32

goroutine 1 [chan receive, 19 minutes]:
testing.(*T).Run(0xc0000a76c0, {0x1736269?, 0x52e7c5?}, 0x18944a8)
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1630 +0x405
testing.runTests.func1(0x25df560?)
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:2036 +0x45
testing.tRunner(0xc0000a76c0, 0xc00052fc88)
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1576 +0x10b
testing.runTests(0xc00029ed20?, {0x25a2b00, 0x4, 0x4}, {0xc000298878?, 0x100c00052fd10?, 0x25de620?})
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:2034 +0x489
testing.(*M).Run(0xc00029ed20)
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1906 +0x63a
main.main()
	_testmain.go:55 +0x1aa

goroutine 22 [chan receive, 20 minutes]:
testing.(*T).Parallel(0xc0000a7860)
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1384 +0x225
github.com/lightninglabs/taproot-assets/tapgarden_test.TestCustodianNewAddr(0xc0000a7860)
	/home/runner/work/taproot-assets/taproot-assets/tapgarden/custodian_test.go:226 +0x33
testing.tRunner(0xc0000a7860, 0x18944b0)
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1629 +0x3ea

goroutine 296 [chan receive, 19 minutes]:
testing.(*T).Parallel(0xc000422ea0)
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1384 +0x225
github.com/lightninglabs/taproot-assets/tapgarden_test.TestAddrMatchesAsset(0xc000422ea0?)
	/home/runner/work/taproot-assets/taproot-assets/tapgarden/custodian_test.go:325 +0x36
testing.tRunner(0xc000422ea0, 0x18944a0)
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1629 +0x3ea

goroutine 318 [select, 19 minutes]:
database/sql.(*DB).connectionOpener(0xc0001faea0, {0x1a1b7b8, 0xc000896550})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 37 [select, 20 minutes]:
database/sql.(*DB).connectionOpener(0xc00007e820, {0x1a1b7b8, 0xc00053dc70})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 62 [select, 20 minutes]:
database/sql.(*DB).connectionOpener(0xc000557ad0, {0x1a1b7b8, 0xc0000a1720})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 51 [select, 20 minutes]:
database/sql.(*DB).connectionOpener(0xc000557520, {0x1a1b7b8, 0xc0000a0820})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 58 [select, 20 minutes]:
database/sql.(*DB).connectionOpener(0xc000557a00, {0x1a1b7b8, 0xc0000a14f0})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 38 [select, 5 minutes]:
database/sql.(*DB).connectionCleaner(0xc00007e820, 0x0?)
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1061 +0xa7
created by database/sql.(*DB).startCleanerLocked
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1048 +0x105

goroutine 314 [select, 19 minutes]:
database/sql.(*DB).connectionOpener(0xc0001fac30, {0x1a1b7b8, 0xc000896320})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 115 [select, 19 minutes]:
database/sql.(*DB).connectionOpener(0xc0000b8d00, {0x1a1b7b8, 0xc00046c730})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 102 [select, 5 minutes]:
database/sql.(*DB).connectionCleaner(0xc00007ec30, 0xc000284100?)
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1061 +0xa7
created by database/sql.(*DB).startCleanerLocked
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1048 +0x105

goroutine 95 [select, 19 minutes]:
database/sql.(*DB).connectionOpener(0xc0000b8c30, {0x1a1b7b8, 0xc00046c500})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 101 [select, 19 minutes]:
database/sql.(*DB).connectionOpener(0xc00007ec30, {0x1a1b7b8, 0xc000495900})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 119 [select, 19 minutes]:
database/sql.(*DB).connectionOpener(0xc0000b8dd0, {0x1a1b7b8, 0xc00046c960})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 310 [select, 19 minutes]:
database/sql.(*DB).connectionOpener(0xc0001fa000, {0x1a1b7b8, 0xc0008960f0})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 335 [select, 5 minutes]:
database/sql.(*DB).connectionCleaner(0xc0001faea0, 0xc000157c20?)
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1061 +0xa7
created by database/sql.(*DB).startCleanerLocked
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1048 +0x105

goroutine 297 [chan receive, 19 minutes]:
testing.(*T).Run(0xc000423040, {0x173943c?, 0x599?}, 0xc0007d2140)
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1630 +0x405
github.com/lightninglabs/taproot-assets/tapgarden_test.TestBatchedAssetIssuance(0xc000423040)
	/home/runner/work/taproot-assets/taproot-assets/tapgarden/planter_test.go:923 +0x4c
testing.tRunner(0xc000423040, 0x18944a8)
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1629 +0x3ea

goroutine 331 [select, 19 minutes]:
database/sql.(*DB).connectionOpener(0xc0000b8a90, {0x1a1b7b8, 0xc000814230})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 659 [select, 19 minutes]:
database/sql.(*DB).connectionOpener(0xc000556820, {0x1a1b7b8, 0xc0008146e0})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 370 [select, 19 minutes]:
github.com/lightningnetwork/lnd/ticker.NewForce.func1()
	/home/runner/work/go/pkg/mod/github.com/lightningnetwork/lnd/ticker@v1.1.0/force.go:43 +0xe5
created by github.com/lightningnetwork/lnd/ticker.NewForce
	/home/runner/work/go/pkg/mod/github.com/lightningnetwork/lnd/ticker@v1.1.0/force.go:40 +0x12a

goroutine 324 [select, 19 minutes]:
database/sql.(*DB).connectionOpener(0xc0000b89c0, {0x1a1b7b8, 0xc000814000})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 660 [select, 5 minutes]:
database/sql.(*DB).connectionCleaner(0xc000556820, 0x0?)
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1061 +0xa7
created by database/sql.(*DB).startCleanerLocked
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1048 +0x105

goroutine 612 [select, 19 minutes]:
github.com/lightninglabs/taproot-assets/tapgarden.(*ChainPlanter).gardener(0xc000556f70)
	/home/runner/work/taproot-assets/taproot-assets/tapgarden/planter.go:456 +0x1cf
created by github.com/lightninglabs/taproot-assets/tapgarden.(*ChainPlanter).Start.func1
	/home/runner/work/taproot-assets/taproot-assets/tapgarden/planter.go:286 +0x3be

goroutine 672 [select]:
github.com/lightningnetwork/lnd/ticker.NewForce.func1()
	/home/runner/work/go/pkg/mod/github.com/lightningnetwork/lnd/ticker@v1.1.0/force.go:43 +0xe5
created by github.com/lightningnetwork/lnd/ticker.NewForce
	/home/runner/work/go/pkg/mod/github.com/lightningnetwork/lnd/ticker@v1.1.0/force.go:40 +0x12a

goroutine 639 [select, 19 minutes]:
database/sql.(*DB).connectionOpener(0xc000556680, {0x1a1b7b8, 0xc000814410})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 949 [select, 5 minutes]:
database/sql.(*DB).connectionCleaner(0xc0005571e0, 0x0?)
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1061 +0xa7
created by database/sql.(*DB).startCleanerLocked
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1048 +0x105

goroutine 647 [select, 19 minutes]:
database/sql.(*DB).connectionOpener(0xc000804000, {0x1a1b7b8, 0xc0000a17c0})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 651 [select, 19 minutes]:
database/sql.(*DB).connectionOpener(0xc0008040d0, {0x1a1b7b8, 0xc0000a1e50})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 929 [select, 19 minutes]:
database/sql.(*DB).connectionOpener(0xc000804340, {0x1a1b7b8, 0xc00083dd60})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 688 [select, 19 minutes]:
github.com/lightninglabs/taproot-assets/tapgarden.(*ChainPlanter).gardener(0xc000557d40)
	/home/runner/work/taproot-assets/taproot-assets/tapgarden/planter.go:456 +0x1cf
created by github.com/lightninglabs/taproot-assets/tapgarden.(*ChainPlanter).Start.func1
	/home/runner/work/taproot-assets/taproot-assets/tapgarden/planter.go:286 +0x3be

goroutine 965 [select, 19 minutes]:
database/sql.(*DB).connectionOpener(0xc000804820, {0x1a1b7b8, 0xc00083df90})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 941 [select, 19 minutes]:
database/sql.(*DB).connectionOpener(0xc000556a90, {0x1a1b7b8, 0xc0004facd0})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 998 [select, 19 minutes]:
github.com/lightninglabs/taproot-assets/tapgarden.(*ChainPlanter).gardener(0xc00007f450)
	/home/runner/work/taproot-assets/taproot-assets/tapgarden/planter.go:456 +0x1cf
created by github.com/lightninglabs/taproot-assets/tapgarden.(*ChainPlanter).Start.func1
	/home/runner/work/taproot-assets/taproot-assets/tapgarden/planter.go:286 +0x3be

goroutine 948 [select, 19 minutes]:
database/sql.(*DB).connectionOpener(0xc0005571e0, {0x1a1b7b8, 0xc0004faf50})
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:1218 +0x8d
created by database/sql.OpenDB
	/opt/hostedtoolcache/go/1.20.4/x64/src/database/sql/sql.go:791 +0x18d

goroutine 961 [select]:
github.com/lightningnetwork/lnd/ticker.NewForce.func1()
	/home/runner/work/go/pkg/mod/github.com/lightningnetwork/lnd/ticker@v1.1.0/force.go:43 +0xe5
created by github.com/lightningnetwork/lnd/ticker.NewForce
	/home/runner/work/go/pkg/mod/github.com/lightningnetwork/lnd/ticker@v1.1.0/force.go:40 +0x12a

goroutine 1264 [select, 19 minutes]:
github.com/lightninglabs/taproot-assets/tapgarden.(*BatchCaretaker).assetCultivator(0xc000262d20)
	/home/runner/work/taproot-assets/taproot-assets/tapgarden/caretaker.go:290 +0x39c
created by github.com/lightninglabs/taproot-assets/tapgarden.(*BatchCaretaker).Start.func1
	/home/runner/work/taproot-assets/taproot-assets/tapgarden/caretaker.go:126 +0x70

goroutine 960 [chan send, 19 minutes]:
github.com/lightninglabs/taproot-assets/tapgarden.(*MockChainBridge).SendConfNtfn(...)
	/home/runner/work/taproot-assets/taproot-assets/tapgarden/mock.go:256
github.com/lightninglabs/taproot-assets/tapgarden_test.(*mintingTestHarness).assertConfReqSent.func1()
	/home/runner/work/taproot-assets/taproot-assets/tapgarden/planter_test.go:506 +0xfd
github.com/lightninglabs/taproot-assets/tapgarden_test.testMintingCancelFinalize(0xc000838300)
	/home/runner/work/taproot-assets/taproot-assets/tapgarden/planter_test.go:876 +0x732
github.com/lightninglabs/taproot-assets/tapgarden_test.TestBatchedAssetIssuance.func1(0xc00061bfb0?)
	/home/runner/work/taproot-assets/taproot-assets/tapgarden/planter_test.go:927 +0x38
testing.tRunner(0xc00097f860, 0xc0007d2140)
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
	/opt/hostedtoolcache/go/1.20.4/x64/src/testing/testing.go:1629 +0x3ea
FAIL	github.com/lightninglabs/taproot-assets/tapgarden	1200.036s
```

### PR DESCRIPTION
**Pull request by jharveyb**
Fixes #360 and #562 .

I found a few problems in the caretaker cancellation error reporting and cancellation, which manifested as an intermittent deadlock in the caretaker when running the minter tests under the race detector / with the `unit-race` target. The other test that revealed issues was deliberately causing failures in the caretaker as part of testing fee estimation, but that itest will be in a separate PR.

I verified these fixes locally by running 100 iterations of `TestBatchAssetIssuance` under standard conditions / with `make unit`, and under the race detector / with `make unit-race`.

One possible TODO is adding extra coverage for when the caretaker is cancelled, but I think the existing unit tests already cover the main partitions of before and after `BatchStateBroadcast`.

### CODE REVIEW

File: tapgarden/planter.go [hunk 1]
```diff
@@ -624,6 +625,18 @@ func (c *ChainPlanter) gardener() {
...
+					// be saved.
+					stopErr := caretaker.Stop()
+					if stopErr != nil {
+						log.Warnf("unable to stop "+
+							"caretaker "+
+							"gracefully: %v", err)
+					}
+
+					delete(c.caretakers, batchKeySerial)
+					c.pendingBatch = nil
```
Comment (GeorgeTsagk) [inline tapgarden/planter.go:639]: Is the required UX here that the user will repeat all the minting calls in order for the batch to be formed again?

Could also feed the seedlings of that batch back into `c.seedlingReqs` and let the process repeat healthily?

**Comment by jharveyb** [comment]
From a peek at the coverage data, current unit tests don't cover:

- Using the actual `FinalizeBatch()` exposed function, and instead trigger the batch ticker directly
- Caretaker error after a planter request for batch finalization
- The negative cases when waiting for TX confirmation
- - error from conf registration, context set to Done, a cancel request, or an empty confEvent
- - Similar lack of coverage for those cases after receiving TX confirmation and before forwarding to another minter goroutine

File: tapgarden/planter.go (hunk 1 above)
Comment (jharveyb) [reply tapgarden/planter.go:639]: I think so? I'm not sure if always trying to re-submit and finalize the batch would help in all cases, or how that won't lead to an infinite loop in cases of an error `tapd` can't resolve like insufficient funds in the backing `lnd` wallet.

Maybe it's worth trying to write this failed batch to disk, and we could later add a way to easily resubmit batches we have stored that are in a cancelled state.


So resubmission would still be manual but at least you wouldn't have to recreate each mint request.

Comment (jharveyb) [reply tapgarden/planter.go]: Actually this batch will already be on disk, just not with a `Cancelled` state. This feels like a part of #710 tbh. Going to leave as-is since the `Cancelled` states signal intentional failure to finalize a batch vs. an error that caused finalization to fail.

**Comment by jharveyb** [comment]
Ready for review, coverage is up 1.6% for the `tapgarden` package and 6.5% for the planter. Ran this under 100 iterations of the race detector without issue.

File: tapgarden/caretaker.go [hunk 2]
```diff
@@ -244,22 +262,20 @@ func (b *BatchCaretaker) advanceStateUntil(currentState,
...
-			// TODO(jhb): Use concrete error types for caretaker
-			// shutdown cases
-			// If the batch was cancellable, the finalState of the
-			// cancel response will be non-nil. If the cancellation
-			// failed, that error will be handled by the planter.
-			// At this point, the caretaker should always shut down
-			// gracefully.
-			if cancelResp.finalState != nil {
+			cancelErr := b.Cancel()
+			if cancelErr == nil {
```
Comment (guggero) [inline tapgarden/caretaker.go:270]: Shouldn't we turn around the logic around the error being nil vs. non-nil? I see this replicates the previous logic, but I would expect a `cancelErr != nil` here rather.

**Review by guggero — APPROVED** [review]
Very nice! Just a couple of nits, otherwise LGTM :tada:

File: make/testing_flags.mk [hunk 3]
```diff
@@ -19,6 +20,7 @@ ifneq ($(pkg),)
 UNITPKG := $(PKG)/$(pkg)
 UNIT_TARGETED = yes
 COVER_PKG = $(PKG)/$(pkg)
+RACE_PKG = echo $(PKG)/$(pkg)
```
[the remark this answers is not in the document]
Comment (jharveyb) [reply make/testing_flags.mk:23]: no, good catch!

File: tapgarden/planter.go [hunk 4]
```diff
@@ -597,8 +598,8 @@ func (c *ChainPlanter) gardener() {
 				}
 
 				batchKey := c.pendingBatch.BatchKey.PubKey
-				log.Infof("Finalizing batch %x",
-					batchKey.SerializeCompressed())
+				batchKeySerial := asset.ToSerialized(batchKey)
+				log.Infof("Finalizing batch %x", batchKeySerial)
```
[the remark this answers is not in the document]
Comment (jharveyb) [reply tapgarden/planter.go:602]: I checked the logs and it is working as expected - I think we have another places where we don't use `%x` with `[]byte` for logging like:

https://github.com/lightninglabs/taproot-assets/blob/eb79a0766f593fe8bfa1866a212740ed8c6a34b2/tapgarden/planter.go#L361

File: tapgarden/caretaker.go (hunk 2 above)
Comment (jharveyb) [reply tapgarden/caretaker.go:270]: I agree the use of `Cancel()` is a bit confusing - we send the error from the attempt to cancel back to the planter in `Cancel()` and this error is only about if cancellation was attempted in `Cancel()`.

So if cancellation was possible and attempted, this err is nil and we shut down. If cancellation was not possible, we return an error and keep running.

I'll add detail on that for the doc for `Cancel()`.

**Comment by dstadulis** [comment]
@ffranr is starting review to unblock the merge queue

File: tapgarden/caretaker.go [hunk 5]
```diff
@@ -216,15 +220,29 @@ func (b *BatchCaretaker) Cancel() CancelResp {
...
+		cancelResp = CancelResp{nil, err}
 	}
+
+	b.cfg.CancelRespChan <- cancelResp
+
+	// If the batch was cancellable, the finalState of the cancel response
+	// will be non-nil. If the cancellation failed, that error will be
+	// handled by the planter. At this point, the caretaker should always
+	// shut down gracefully.
+	if cancelResp.finalState != nil {
```
Comment (ffranr) [inline tapgarden/caretaker.go:236]: It seems to me that `finalState` is used indirectly to indicate whether the batch was successfully cancelled or not.

Perhaps we should add a new bool flag to `CancelResp` called `BatchCancelSuccessful` or something like that which would handle that state explicitly. This might help us get rid of some comments.

File: tapgarden/caretaker.go [hunk 6]
```diff
@@ -906,24 +916,31 @@ func (b *BatchCaretaker) stateStep(currentState BatchState) (BatchState, error)
...
-				if cancelErr == nil {
+			for !confSend {
+				select {
+				case b.confEvent <- confEvent:
+					confSend = true
+
+				case <-confCtx.Done():
+					log.Debugf("Skipping TX confirmation, " +
+						"context done")
+					confSend = true
```
Comment (ffranr) [inline tapgarden/caretaker.go:936]: Is this line correct? If the context is done, can we really set `confSend` to `true`? Maybe we should add a comment here.

**Review by ffranr — APPROVED** [review]
I can imagine that this wasn't easy to debug! Nice work.

File: tapgarden/caretaker.go (hunk 5 above)
Comment (jharveyb) [reply tapgarden/caretaker.go:236]: Good catch! Reading this again the planter and the other callsites for `Cancel()` don't actually need the final batch state, just if the batch was cancellable. So `finalState` could be replaced with a bool.

We still want to report any potential errors from the DB update.
