### PR TITLE
rpcserver: return early on rejected quote

### LINKED ISSUE #1571: [bug]: `AddInvoice` takes 120 seconds to fail with "could not create any quotes for the invoice"
I try to create an invoice when all 4 connected edge nodes that have a price that is outside of the range of
```
taproot-assets.experimental.rfq.acceptpricedeviationppm
```
.

I would expect this to fail within a few seconds, but it takes 120 seconds to fail instead.

Looking at the log, it seems as though after the "Buy accept price is not within acceptable bounds", it waits 30 seconds to get "error while trying to acquire a buy order for invoice: error adding buy order: timeout waiting for response" before moving on to the next peer. I think there is something wrong with the way it is rejecting the buy price and then failing to move on quickly

```
2025-05-27 17:07:22.386 [INF] LITD: Handling gRPC request: /tapchannelrpc.TaprootAssetChannels/AddInvoice
2025-05-27 17:07:22.387 [DBG] RPCS: [/tapchannelrpc.TaprootAssetChannels/AddInvoice] requested
2025-05-27 17:07:22.387 [DBG] RPCS: [/lnrpc.Lightning/ListChannels] requested
2025-05-27 17:07:22.388 [DBG] RPCS: [listchannels] fetched 5 channels from DB
2025-05-27 17:07:22.390 [DBG] RPCS: [/lnrpc.Lightning/ListChannels] requested
2025-05-27 17:07:22.391 [DBG] RPCS: [listchannels] fetched 5 channels from DB
2025-05-27 17:07:22.393 [DBG] RFQS: Querying price oracle for bid price (asset_specifier=AssetSpecifier(id=af6ae4f3e3c3b7ba1932890b3f8d8ba8d5398ff446623a3c8055394617d8b511, group_pub_key=), asset_max_amt=Some(22
0000000), payment_max_amt=None, asset_rate_hint=None)
2025-05-27 17:07:22.393 [DBG] RFQS: Manager handling outgoing message: BuyRequest(peer=0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462, id=f4614bf749a2d5e0a293ee67f3591cf48a5775e102b58b6ef7184
e1c10d9710b, asset=AssetSpecifier(id=af6ae4f3e3c3b7ba1932890b3f8d8ba8d5398ff446623a3c8055394617d8b511, group_pub_key=), max_asset_amount=220000000, asset_rate_hint=AssetRate(rate=10149999999.0000000000, expiry=2
025-05-27T17:07:57Z))
2025-05-27 17:07:22.393 [DBG] RFQS: Stream handling outgoing message: BuyRequest(peer=0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462, id=f4614bf749a2d5e0a293ee67f3591cf48a5775e102b58b6ef7184e
1c10d9710b, asset=AssetSpecifier(id=af6ae4f3e3c3b7ba1932890b3f8d8ba8d5398ff446623a3c8055394617d8b511, group_pub_key=), max_asset_amount=220000000, asset_rate_hint=AssetRate(rate=10149999999.0000000000, expiry=20
25-05-27T17:07:57Z))
2025-05-27 17:07:22.393 [DBG] RPCS: [/lnrpc.Lightning/SendCustomMessage] requested
2025-05-27 17:07:22.393 [DBG] PEER: Peer(0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462): Sending custom(type=52884) to 0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462@172.
99.0.13:60880
2025-05-27 17:07:22.399 [DBG] PEER: Peer(0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462): Received custom(type=52885) from 0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462@1
72.99.0.13:60880
2025-05-27 17:07:22.399 [DBG] SRVR: Custom message received: peer=0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462, type=52885
2025-05-27 17:07:22.399 [DBG] RFQS: Stream handling incoming message: BuyAccept(peer=0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462, id=f4614bf749a2d5e0a293ee67f3591cf48a5775e102b58b6ef7184e1
c10d9710b, asset_rate=AssetRate(rate=12000000000, expiry=2025-05-27T18:07:22Z), scid=17805067009257992459)
2025-05-27 17:07:22.400 [DBG] RFQS: Manager handling incoming message: BuyAccept(peer=0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462, id=f4614bf749a2d5e0a293ee67f3591cf48a5775e102b58b6ef7184e
1c10d9710b, asset_rate=AssetRate(rate=12000000000, expiry=2025-05-27T18:07:22Z), scid=17805067009257992459)
2025-05-27 17:07:22.400 [DBG] RFQS: Querying price oracle for bid price (asset_specifier=AssetSpecifier(id=af6ae4f3e3c3b7ba1932890b3f8d8ba8d5398ff446623a3c8055394617d8b511, group_pub_key=), asset_max_amt=Some(22
0000000), payment_max_amt=None, asset_rate_hint=Some({12000000000 2025-05-27 18:07:22 +0000 UTC}))
2025-05-27 17:07:22.400 [DBG] RFQS: Buy accept price is not within acceptable bounds (peer_asset_rate=AssetRate(rate=12000000000, expiry=2025-05-27T18:07:22Z), oracle_asset_rate=AssetRate(rate=10149999999.000000
0000, expiry=2025-05-27T17:07:57Z))
2025-05-27 17:07:36.841 [DBG] PEER: Peer(02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2): Sending Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4a
ac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) to 02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2@172.99.0.15:58818
2025-05-27 17:07:36.842 [DBG] PEER: Peer(02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2): Received Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4
aac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) from 02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2@172.99.0.15:58818
2025-05-27 17:07:36.842 [DBG] PEER: Peer(02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2): Sending Pong(len(pong_bytes)=2961) to 02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f9
4f2@172.99.0.15:58818
2025-05-27 17:07:36.843 [DBG] PEER: Peer(02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2): Received Pong(len(pong_bytes)=3098) from 02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f
2f94f2@172.99.0.15:58818
2025-05-27 17:07:37.330 [DBG] HLCK: Health check: chain backend invoking success callback
2025-05-27 17:07:46.688 [DBG] PEER: Peer(0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462): Sending Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4aac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) to 0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462@172.99.0.13:60880
2025-05-27 17:07:46.688 [DBG] PEER: Peer(0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462): Received Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4aac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) from 0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462@172.99.0.13:60880
2025-05-27 17:07:46.688 [DBG] PEER: Peer(0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462): Sending Pong(len(pong_bytes)=2124) to 0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462@172.99.0.13:60880
2025-05-27 17:07:46.689 [DBG] PEER: Peer(0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462): Received Pong(len(pong_bytes)=1124) from 0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462@172.99.0.13:60880
2025-05-27 17:07:49.745 [DBG] PEER: Peer(02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9): Sending Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4aac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) to 02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9@172.99.0.8:43900
2025-05-27 17:07:49.745 [DBG] PEER: Peer(02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9): Received Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4aac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) from 02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9@172.99.0.8:43900
2025-05-27 17:07:49.745 [DBG] PEER: Peer(02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9): Sending Pong(len(pong_bytes)=2328) to 02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9@172.99.0.8:43900
2025-05-27 17:07:49.746 [DBG] PEER: Peer(02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9): Received Pong(len(pong_bytes)=1371) from 02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9@172.99.0.8:43900
2025-05-27 17:07:52.394 [ERR] RPCS: error while trying to acquire a buy order for invoice: error adding buy order: timeout waiting for response (peer=0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462)
2025-05-27 17:07:52.394 [DBG] RPCS: [/lnrpc.Lightning/ListChannels] requested
2025-05-27 17:07:52.397 [DBG] RPCS: [listchannels] fetched 5 channels from DB
2025-05-27 17:07:52.398 [DBG] RFQS: Querying price oracle for bid price (asset_specifier=AssetSpecifier(id=af6ae4f3e3c3b7ba1932890b3f8d8ba8d5398ff446623a3c8055394617d8b511, group_pub_key=), asset_max_amt=Some(220000000), payment_max_amt=None, asset_rate_hint=None)
2025-05-27 17:07:52.399 [DBG] RFQS: Manager handling outgoing message: BuyRequest(peer=0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e, id=cfec6500822ab31f912396c25705de8e213ebaf90b8df3d5f46be1f3fdb8b890, asset=AssetSpecifier(id=af6ae4f3e3c3b7ba1932890b3f8d8ba8d5398ff446623a3c8055394617d8b511, group_pub_key=), max_asset_amount=220000000, asset_rate_hint=AssetRate(rate=10149999999.0000000000, expiry=2025-05-27T17:08:27Z))
2025-05-27 17:07:52.399 [DBG] RFQS: Stream handling outgoing message: BuyRequest(peer=0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e, id=cfec6500822ab31f912396c25705de8e213ebaf90b8df3d5f46be1f3fdb8b890, asset=AssetSpecifier(id=af6ae4f3e3c3b7ba1932890b3f8d8ba8d5398ff446623a3c8055394617d8b511, group_pub_key=), max_asset_amount=220000000, asset_rate_hint=AssetRate(rate=10149999999.0000000000, expiry=2025-05-27T17:08:27Z))
2025-05-27 17:07:52.399 [DBG] RPCS: [/lnrpc.Lightning/SendCustomMessage] requested
2025-05-27 17:07:52.399 [DBG] PEER: Peer(0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e): Sending custom(type=52884) to 0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e@172.99.0.14:57852
2025-05-27 17:07:52.412 [DBG] PEER: Peer(0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e): Received custom(type=52885) from 0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e@172.99.0.14:57852
2025-05-27 17:07:52.412 [DBG] SRVR: Custom message received: peer=0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e, type=52885
2025-05-27 17:07:52.412 [DBG] RFQS: Stream handling incoming message: BuyAccept(peer=0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e, id=cfec6500822ab31f912396c25705de8e213ebaf90b8df3d5f46be1f3fdb8b890, asset_rate=AssetRate(rate=12000000000, expiry=2025-05-27T18:07:52Z), scid=17612419205812500624)
2025-05-27 17:07:52.412 [DBG] RFQS: Manager handling incoming message: BuyAccept(peer=0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e, id=cfec6500822ab31f912396c25705de8e213ebaf90b8df3d5f46be1f3fdb8b890, asset_rate=AssetRate(rate=12000000000, expiry=2025-05-27T18:07:52Z), scid=17612419205812500624)
2025-05-27 17:07:52.412 [DBG] RFQS: Querying price oracle for bid price (asset_specifier=AssetSpecifier(id=af6ae4f3e3c3b7ba1932890b3f8d8ba8d5398ff446623a3c8055394617d8b511, group_pub_key=), asset_max_amt=Some(220000000), payment_max_amt=None, asset_rate_hint=Some({12000000000 2025-05-27 18:07:52 +0000 UTC}))
2025-05-27 17:07:52.412 [DBG] RFQS: Buy accept price is not within acceptable bounds (peer_asset_rate=AssetRate(rate=12000000000, expiry=2025-05-27T18:07:52Z), oracle_asset_rate=AssetRate(rate=10149999999.0000000000, expiry=2025-05-27T17:08:27Z))
2025-05-27 17:08:11.520 [DBG] PEER: Peer(0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e): Sending Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4aac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) to 0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e@172.99.0.14:57852
2025-05-27 17:08:11.520 [DBG] PEER: Peer(0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e): Received Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4aac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) from 0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e@172.99.0.14:57852
2025-05-27 17:08:11.520 [DBG] PEER: Peer(0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e): Sending Pong(len(pong_bytes)=1134) to 0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e@172.99.0.14:57852
2025-05-27 17:08:11.521 [DBG] PEER: Peer(0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e): Received Pong(len(pong_bytes)=1989) from 0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e@172.99.0.14:57852
2025-05-27 17:08:22.399 [ERR] RPCS: error while trying to acquire a buy order for invoice: error adding buy order: timeout waiting for response (peer=0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e)
2025-05-27 17:08:22.399 [DBG] RPCS: [/lnrpc.Lightning/ListChannels] requested
2025-05-27 17:08:22.401 [DBG] RPCS: [listchannels] fetched 5 channels from DB
2025-05-27 17:08:22.402 [DBG] RFQS: Querying price oracle for bid price (asset_specifier=AssetSpecifier(id=af6ae4f3e3c3b7ba1932890b3f8d8ba8d5398ff446623a3c8055394617d8b511, group_pub_key=), asset_max_amt=Some(220000000), payment_max_amt=None, asset_rate_hint=None)
2025-05-27 17:08:22.403 [DBG] RFQS: Manager handling outgoing message: BuyRequest(peer=02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2, id=22b8448dd285eccd8328ec48977d34b5b0badbc5bb0aa9a4f574e987922211df, asset=AssetSpecifier(id=af6ae4f3e3c3b7ba1932890b3f8d8ba8d5398ff446623a3c8055394617d8b511, group_pub_key=), max_asset_amount=220000000, asset_rate_hint=AssetRate(rate=10149999999.0000000000, expiry=2025-05-27T17:08:57Z))
2025-05-27 17:08:22.403 [DBG] RFQS: Stream handling outgoing message: BuyRequest(peer=02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2, id=22b8448dd285eccd8328ec48977d34b5b0badbc5bb0aa9a4f574e987922211df, asset=AssetSpecifier(id=af6ae4f3e3c3b7ba1932890b3f8d8ba8d5398ff446623a3c8055394617d8b511, group_pub_key=), max_asset_amount=220000000, asset_rate_hint=AssetRate(rate=10149999999.0000000000, expiry=2025-05-27T17:08:57Z))
2025-05-27 17:08:22.403 [DBG] RPCS: [/lnrpc.Lightning/SendCustomMessage] requested
2025-05-27 17:08:22.403 [DBG] PEER: Peer(02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2): Sending custom(type=52884) to 02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2@172.99.0.15:58818
2025-05-27 17:08:22.407 [DBG] PEER: Peer(02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2): Received custom(type=52885) from 02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2@172.99.0.15:58818
2025-05-27 17:08:22.407 [DBG] SRVR: Custom message received: peer=02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2, type=52885
2025-05-27 17:08:22.407 [DBG] RFQS: Stream handling incoming message: BuyAccept(peer=02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2, id=22b8448dd285eccd8328ec48977d34b5b0badbc5bb0aa9a4f574e987922211df, asset_rate=AssetRate(rate=12000000000, expiry=2025-05-27T18:08:22Z), scid=17687018405072343519)
2025-05-27 17:08:22.407 [DBG] RFQS: Manager handling incoming message: BuyAccept(peer=02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2, id=22b8448dd285eccd8328ec48977d34b5b0badbc5bb0aa9a4f574e987922211df, asset_rate=AssetRate(rate=12000000000, expiry=2025-05-27T18:08:22Z), scid=17687018405072343519)
2025-05-27 17:08:22.407 [DBG] RFQS: Querying price oracle for bid price (asset_specifier=AssetSpecifier(id=af6ae4f3e3c3b7ba1932890b3f8d8ba8d5398ff446623a3c8055394617d8b511, group_pub_key=), asset_max_amt=Some(220000000), payment_max_amt=None, asset_rate_hint=Some({12000000000 2025-05-27 18:08:22 +0000 UTC}))
2025-05-27 17:08:22.407 [DBG] RFQS: Buy accept price is not within acceptable bounds (peer_asset_rate=AssetRate(rate=12000000000, expiry=2025-05-27T18:08:22Z), oracle_asset_rate=AssetRate(rate=10149999999.0000000000, expiry=2025-05-27T17:08:57Z))
2025-05-27 17:08:36.842 [DBG] PEER: Peer(02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2): Sending Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4aac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) to 02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2@172.99.0.15:58818
2025-05-27 17:08:36.842 [DBG] PEER: Peer(02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2): Received Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4aac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) from 02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2@172.99.0.15:58818
2025-05-27 17:08:36.842 [DBG] PEER: Peer(02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2): Received Pong(len(pong_bytes)=1176) from 02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2@172.99.0.15:58818
2025-05-27 17:08:36.842 [DBG] PEER: Peer(02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2): Sending Pong(len(pong_bytes)=3685) to 02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2@172.99.0.15:58818
2025-05-27 17:08:37.329 [DBG] HLCK: Health check: chain backend invoking success callback
2025-05-27 17:08:46.688 [DBG] PEER: Peer(0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462): Sending Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4aac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) to 0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462@172.99.0.13:60880
2025-05-27 17:08:46.688 [DBG] PEER: Peer(0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462): Received Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4aac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) from 0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462@172.99.0.13:60880
2025-05-27 17:08:46.688 [DBG] PEER: Peer(0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462): Sending Pong(len(pong_bytes)=100) to 0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462@172.99.0.13:60880
2025-05-27 17:08:46.689 [DBG] PEER: Peer(0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462): Received Pong(len(pong_bytes)=980) from 0206982a7f16ab51e3f943fa16f8a232f3ee0f66b6ff2c7fb85d03a8e33d845462@172.99.0.13:60880
2025-05-27 17:08:49.745 [DBG] PEER: Peer(02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9): Sending Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4aac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) to 02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9@172.99.0.8:43900
2025-05-27 17:08:49.745 [DBG] PEER: Peer(02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9): Received Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4aac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) from 02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9@172.99.0.8:43900
2025-05-27 17:08:49.746 [DBG] PEER: Peer(02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9): Received Pong(len(pong_bytes)=540) from 02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9@172.99.0.8:43900
2025-05-27 17:08:49.746 [DBG] PEER: Peer(02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9): Sending Pong(len(pong_bytes)=2178) to 02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9@172.99.0.8:43900
2025-05-27 17:08:52.403 [ERR] RPCS: error while trying to acquire a buy order for invoice: error adding buy order: timeout waiting for response (peer=02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2)
2025-05-27 17:08:52.403 [DBG] RPCS: [/lnrpc.Lightning/ListChannels] requested
2025-05-27 17:08:52.404 [DBG] RPCS: [listchannels] fetched 5 channels from DB
2025-05-27 17:08:52.406 [DBG] RFQS: Querying price oracle for bid price (asset_specifier=AssetSpecifier(id=af6ae4f3e3c3b7ba1932890b3f8d8ba8d5398ff446623a3c8055394617d8b511, group_pub_key=), asset_max_amt=Some(220000000), payment_max_amt=None, asset_rate_hint=None)
2025-05-27 17:08:52.406 [DBG] RFQS: Manager handling outgoing message: BuyRequest(peer=02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9, id=c8d75023895d98dd9e52abe0ab1dddeed51f7a395fdef331f472e0ed1658343f, asset=AssetSpecifier(id=af6ae4f3e3c3b7ba1932890b3f8d8ba8d5398ff446623a3c8055394617d8b511, group_pub_key=), max_asset_amount=220000000, asset_rate_hint=AssetRate(rate=10149999999.0000000000, expiry=2025-05-27T17:09:27Z))
2025-05-27 17:08:52.406 [DBG] RFQS: Stream handling outgoing message: BuyRequest(peer=02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9, id=c8d75023895d98dd9e52abe0ab1dddeed51f7a395fdef331f472e0ed1658343f, asset=AssetSpecifier(id=af6ae4f3e3c3b7ba1932890b3f8d8ba8d5398ff446623a3c8055394617d8b511, group_pub_key=), max_asset_amount=220000000, asset_rate_hint=AssetRate(rate=10149999999.0000000000, expiry=2025-05-27T17:09:27Z))
2025-05-27 17:08:52.406 [DBG] RPCS: [/lnrpc.Lightning/SendCustomMessage] requested
2025-05-27 17:08:52.407 [DBG] PEER: Peer(02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9): Sending custom(type=52884) to 02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9@172.99.0.8:43900
2025-05-27 17:08:52.420 [DBG] PEER: Peer(02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9): Received custom(type=52885) from 02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9@172.99.0.8:43900
2025-05-27 17:08:52.420 [DBG] SRVR: Custom message received: peer=02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9, type=52885
2025-05-27 17:08:52.420 [DBG] RFQS: Stream handling incoming message: BuyAccept(peer=02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9, id=c8d75023895d98dd9e52abe0ab1dddeed51f7a395fdef331f472e0ed1658343f, asset_rate=AssetRate(rate=12000000000, expiry=2025-05-27T18:08:52Z), scid=17614388401486181439)
2025-05-27 17:08:52.420 [DBG] RFQS: Manager handling incoming message: BuyAccept(peer=02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9, id=c8d75023895d98dd9e52abe0ab1dddeed51f7a395fdef331f472e0ed1658343f, asset_rate=AssetRate(rate=12000000000, expiry=2025-05-27T18:08:52Z), scid=17614388401486181439)
2025-05-27 17:08:52.420 [DBG] RFQS: Querying price oracle for bid price (asset_specifier=AssetSpecifier(id=af6ae4f3e3c3b7ba1932890b3f8d8ba8d5398ff446623a3c8055394617d8b511, group_pub_key=), asset_max_amt=Some(220000000), payment_max_amt=None, asset_rate_hint=Some({12000000000 2025-05-27 18:08:52 +0000 UTC}))
2025-05-27 17:08:52.420 [DBG] RFQS: Buy accept price is not within acceptable bounds (peer_asset_rate=AssetRate(rate=12000000000, expiry=2025-05-27T18:08:52Z), oracle_asset_rate=AssetRate(rate=10149999999.0000000000, expiry=2025-05-27T17:09:27Z))
2025-05-27 17:09:11.520 [DBG] PEER: Peer(0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e): Sending Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4aac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) to 0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e@172.99.0.14:57852
2025-05-27 17:09:11.520 [DBG] PEER: Peer(0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e): Received Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4aac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) from 0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e@172.99.0.14:57852
2025-05-27 17:09:11.520 [DBG] PEER: Peer(0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e): Sending Pong(len(pong_bytes)=828) to 0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e@172.99.0.14:57852
2025-05-27 17:09:11.520 [DBG] PEER: Peer(0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e): Received Pong(len(pong_bytes)=2870) from 0240610c3e9a8d086fe6209a84f8a91afd084abb26d036fd19c8e4473c09537c8e@172.99.0.14:57852
2025-05-27 17:09:22.406 [ERR] RPCS: error while trying to acquire a buy order for invoice: error adding buy order: timeout waiting for response (peer=02c74b65565e7d004865ce5c9795d399fc9b3802e7888215fe1c15867b303cf6f9)
2025-05-27 17:09:22.406 [ERR] RPCS: [/tapchannelrpc.TaprootAssetChannels/AddInvoice]: could not create any quotes for the invoice
2025-05-27 17:09:36.841 [DBG] PEER: Peer(02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2): Sending Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4aac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) to 02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2@172.99.0.15:58818
2025-05-27 17:09:36.842 [DBG] PEER: Peer(02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2): Received Ping(ping_bytes=000000204fe382d257a72f00ff7f4d820874800edcd773a876ae97ba0c0ee45a2b560760f2c4aac7ff3c9cdbcf56e8cda3ccfd2773f41b6acfea46f57996856e1f7dcee264eb3568ffff7f2000000000) from 02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2@172.99.0.15:58818
2025-05-27 17:09:36.842 [DBG] PEER: Peer(02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2): Sending Pong(len(pong_bytes)=157) to 02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2@172.99.0.15:58818
2025-05-27 17:09:36.843 [DBG] PEER: Peer(02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2): Received Pong(len(pong_bytes)=743) from 02965de0b7f611793f7c4d63b97c1a7179efb5ed41f91e3f52f267ccaf4f2f94f2@172.99.0.15:58818
```

### PR DESCRIPTION
**Pull request by GeorgeTsagk**
## Description

When an RFQ negotiation fails we return the `rfq.InvalidQuoteRespEvent` event to the RPC subscriber. Previously this message was ignored, causing the RPC endpoint to only return when the timeout occured. Now we immediatelly return when an RFQ negotiation failure occurs

 Closes #1571

### CODE REVIEW

**Comment by ZZiigguurraatt** [comment]
Any reason why you are not including this in https://github.com/lightninglabs/taproot-assets/pull/1613 ? Or are you planning to merge this first and rebase on top of it?

**Comment by ZZiigguurraatt** [comment]
Is this the fix for https://github.com/lightninglabs/taproot-assets/issues/1571 ?

**Comment by GeorgeTsagk** [comment]
> Any reason why you are not including this in https://github.com/lightninglabs/taproot-assets/pull/1613 ? Or are you planning to merge this first and rebase on top of it?

Just to separate the concerns, referenced PR is already quite large and has a scope of its own.

> Is this the fix for https://github.com/lightninglabs/taproot-assets/issues/1571 ?

Yes, should fix that issue.

File: rfq/negotiator.go [hunk 1]
```diff
@@ -155,82 +155,79 @@ func (n *Negotiator) queryBidFromPriceOracle(assetSpecifier asset.Specifier,
 // HandleOutgoingBuyOrder handles an outgoing buy order by constructing buy
 // requests and passing them to the outgoing messages channel. These requests
 // are sent to peers.
-func (n *Negotiator) HandleOutgoingBuyOrder(buyOrder BuyOrder) error {
-	// Query the price oracle for a reasonable bid price. We perform this
-	// query and response handling in a separate goroutine in case it is a
-	// remote service and takes a long time to respond.
-	n.Wg.Add(1)
```
Comment (GeorgeTsagk) [inline rfq/negotiator.go:162]: @ffranr I realized that removing this was not very crucial. Here's my rationale:

If the oracle is slow then the caller of the function will have to block anyway in order to get the response item. Instead if we make this piece of code synchronous:

a) We get the opportunity to return the error to the caller, which was previously silently forwarded to `n.cfg.ErrChan` which was only getting logged. The caller would hang until some timeout would hit.

b) We also have a simple way of immediately returning the `rfqmsg.ID` to the caller, which is crucial for filtering the global subscription stream for RFQ updates based on that ID (the only unique field across RFQ requests)

File: rpcserver.go [hunk 2]
```diff
@@ -7386,18 +7386,29 @@ func (r *rpcServer) AddAssetBuyOrder(ctx context.Context,
...
+		targetEventType = *rfq.PeerAcceptedBuyQuoteEvent
+		rejectEventType = *rfq.InvalidQuoteRespEvent
+	)
+
 	for {
-		type targetEventType = *rfq.PeerAcceptedBuyQuoteEvent
 		select {
 		case event := <-eventSubscriber.NewItemCreated.ChanOut():
+			reject, ok := event.(rejectEventType)
+			if ok && reject.QuoteResponse.MsgID() == id {
```
Comment (GeorgeTsagk) [inline rpcserver.go]: this was tricky to find, as it was unreliable in the itests:

If the rejecting peer replied first, then all callers would read that rejection and assume their quote rejected.

Similarly, if the rejecting peer replied earlier than any other peer their rejection could have been misread by another subscriber.

File: rpcserver.go [hunk 3]
```diff
@@ -7394,10 +7394,26 @@ func (r *rpcServer) AddAssetBuyOrder(ctx context.Context,
...
+	type (
+		targetEventType = *rfq.PeerAcceptedBuyQuoteEvent
+		rejectEventType = *rfq.InvalidQuoteRespEvent
+	)
+
 	for {
-		type targetEventType = *rfq.PeerAcceptedBuyQuoteEvent
 		select {
 		case event := <-eventSubscriber.NewItemCreated.ChanOut():
+			reject, ok := event.(rejectEventType)
```
Comment (guggero) [inline rpcserver.go]: nit: could make these two type casts into a `switch` statement for more clarity. Same below.

File: docs/release-notes/release-notes-0.7.0.md [hunk 4]
```diff
@@ -86,6 +86,10 @@
 
 ## Functional Updates
 
+- When sending a payment or adding an invoice any failed RFQ negotiations will
+  now fail immedietaly, instead of causing a long timeout (30s). This was due
+  to the RPC endpoint ignoring the RFQ rejection response.
```
Comment (guggero) [inline docs/release-notes/release-notes-0.7.0.md]: nit: need to link to the PR to make it pass the CI step.

**Comment by litbot-9000** [comment]
@ffranr: review reminder

File: docs/release-notes/release-notes-0.7.0.md [hunk 5]
```diff
@@ -103,6 +103,12 @@
   balances of asset channels grouped by group key (if grouped assets were used
   in a channel)](https://github.com/lightninglabs/taproot-assets/pull/1691).
 
+- When sending a payment or adding an invoice any failed RFQ negotiations will
+  now fail immedietaly, instead of causing a long timeout (30s). This was due
```
Comment (jtobin) [inline docs/release-notes/release-notes-0.7.0.md]: s/immedietaly/immediately

Comment (GeorgeTsagk) [reply docs/release-notes/release-notes-0.7.0.md]: thanks!
