### PR TITLE
Assorted release maintenance

### LINKED ISSUE #1874: [bug]: release verification differs between environments
### Background

Release verification does not currently work on macOS devices because of different reasons:
1. Usage of `grep -P` in `get-git-tag-name.sh`
2. `gzip` issue: See https://github.com/lightningnetwork/lnd/pull/10268

### Steps to reproduce

Execution of `make release` differs between macOS and Linux environments.

### Expected behavior

manifest result should be the same

### Actual behavior

Tell us what happens instead

### PR DESCRIPTION
**Pull request by jtobin**
Closes #1874, #1877.

See the individual commits for more details, but the TLDR version:

* Adds installation checks (à la the existing GNU tar check) to scripts/release.sh for other required utilities.
* Adjusts the CI release workflow to build with `docker-release` (see commentary in #1877 for rationale).
* Updates and modernizes the release docs (docs/release.md).
* Makes scripts/verify-install.sh work on our official Docker images (i.e., going forward).

### CODE REVIEW

File: scripts/release.sh [hunk 1]
```diff
@@ -125,6 +132,19 @@ function build_release() {
...
+  # coreutils's 'sha256sum'.
+  if ! command -v "shasum" &>/dev/null; then
+    if ! command -v "sha256sum" &>/dev/null; then
+      echo "Either a Perl or GNU coreutils installation is required."
+      exit 1
+    else
+      # coreutils is installed, so use sha256sum instead.
+      shasum_cmd="sha256sum"
+    fi
+  fi
```
[the remark this answers is not in the document]
Comment (jtobin) [reply scripts/release.sh:147]: Huh, shellcheck didn't catch this one.

[the remark this answers is not in the document]
Comment (jtobin) [reply scripts/release.sh:147]: Fixed in 9d998206b1912e94fec13ab69249c24eb4e28de6.

File: scripts/release.sh [hunk 2]
```diff
@@ -189,7 +209,7 @@ required Go version ($goversion)."
 
     # Add the hashes for the individual binaries as well for easy verification
     # of a single installed binary.
-    shasum -a 256 "${dir}/"* >> "manifest-$tag.txt" 
+    "$shasum_cmd" "${dir}/"* >> "manifest-$tag.txt"
```
[the remark this answers is not in the document]
Comment (jtobin) [reply scripts/release.sh]: Fixed in 9d998206b1912e94fec13ab69249c24eb4e28de6 via unquoting.

File: scripts/release.sh [hunk 3]
```diff
@@ -199,7 +219,7 @@ required Go version ($goversion)."
   done
 
   # Add the hash of the packages too, then sort by the second column (name).
-  shasum -a 256 $PACKAGE-* vendor* >> "manifest-$tag.txt"
+  "$shasum_cmd" $PACKAGE-* vendor* >> "manifest-$tag.txt"
```
[the remark this answers is not in the document]
Comment (jtobin) [reply scripts/release.sh]: Fixed in 9d998206b1912e94fec13ab69249c24eb4e28de6 via unquoting.

File: scripts/release.sh [hunk 4]
```diff
@@ -125,6 +132,19 @@ function build_release() {
   local buildtags=$3
   local ldflags=$4
   local goversion=$5
+  local shasum_cmd="shasum -a 256"
+
+  # If we don't have a Perl installation available, then check for
```
Comment (Roasbeef) [inline scripts/release.sh:137]: Where do we rely on perl rn?

File: .github/workflows/release.yaml [hunk 5]
```diff
@@ -37,16 +37,16 @@ jobs:
...
         run: git checkout ${{ env.RELEASE_VERSION }}
 
+      - name: build release helper docker image
+        run: |
+          docker build -t taproot-assets-release-helper \
+            -f make/builder.Dockerfile make/
+
       - name: build release for all architectures
-        run: make release tag=${{ env.RELEASE_VERSION }}
+        run: make docker-release tag=${{ env.RELEASE_VERSION }}
```
Comment (Roasbeef) [inline .github/workflows/release.yaml:49]: Idea is to move to prefer the docker release? 

We should test to see how this impacts the fixes that we had to roll out to ensure that there's enough disk space left for the build. 

Will the subsequent steps also be able to find the release artefacts?

File: docs/release.md [hunk 6]
```diff
@@ -1,125 +1,112 @@
...
 
 ```shell
-$  git clone https://github.com/lightninglabs/taproot-assets.git
-$  cd taproot-assets
-$  git checkout <TAG> # <TAG> is the name of the next release/tag
-$  make docker-release tag=<TAG>
+$ git clone https://github.com/lightninglabs/taproot-assets.git
+$ cd taproot-assets
+$ git checkout "$TAG"
+$ make docker-release tag="$TAG"
```
Comment (Roasbeef) [inline docs/release.md:28]: I think we should be able to speed up the docker-release (at least on mac) using a similar technique as my recent PR to speed up linting.

File: docs/release.md [hunk 7]
```diff
@@ -1,125 +1,112 @@
...
 ```
 
-Where `<TAG>` is the name of the next release of `taproot-assets`.
+Where `$TAG` is the name of the desired release of `taproot-assets`.
 
-### Linux/Windows (WSL)
+Note that you can also run `make release` to avoid the dependency on
```
Comment (Roasbeef) [inline docs/release.md:33]: 👍

File: docs/release.md [hunk 8]
```diff
@@ -1,125 +1,112 @@
...
-example):
+   PGP public keys of Taproot Assets developers can be found in the
+   scripts/keys subdirectory of the repository root.
+
+3. Procure the other release artifacts, either by building the release from
+   source as [described above](#building-a-release), or by downloading
+   the desired archive(s) containing the release binaries from the
+   Taproot Assets [Releases page][ghrelease] on GitHub.
+
+4. Recompute the SHA256 hash of each artifact with e.g.  `shasum -a 256
```
Comment (Roasbeef) [inline docs/release.md:67]: On the `lnd` side, we've recently started to use commands like this that wrap everything all into one: 
```
wget https://dl.google.com/go/go1.24.9.linux-amd64.tar.gz

echo "5b7899591c2dd6e9da1809fde4a2fad842c45d3f6b9deb235ba82216e31e34a6  go1.24.9.linux-amd64.tar.gz" | sha256sum --check
```

File: make/builder.Dockerfile [hunk 9]
```diff
@@ -1,4 +1,4 @@
-FROM golang:1.24.9-bookworm
+FROM golang:1.24.9-bookworm@sha256:737b40b61ce956d738bed59f18ba854d8d67e7a4c4fa63f64437f4c70247ac5b
```
Comment (Roasbeef) [inline make/builder.Dockerfile:1]: 👍

File: scripts/release.sh (hunk 4 above)
Comment (jtobin) [reply scripts/release.sh:137]: shasum relies on it:

```
$ cat $(which shasum) | head -10
#!/usr/bin/perl
    eval 'exec /usr/bin/perl -S $0 ${1+"$@"}'
	if 0; # ^ Run only under a shell
#!perl

	## shasum: filter for computing SHA digests (ref. sha1sum/md5sum)
	##
	## Copyright (C) 2003-2018 Mark Shelor, All Rights Reserved
	##
	## Version: 6.02
```

If it's not available (rarely, but can happen) then we check for GNU coreutils' sha256sum and use that instead.

File: .github/workflows/release.yaml (hunk 5 above)
Comment (jtobin) [reply .github/workflows/release.yaml:49]: Yeah good point re: available space, I'll test by pushing a dev tag to this branch.

**Comment by jtobin** [comment]
I've since tested CI with the changes here and can confirm that everything works (no disk issues, etc.). A stripped-down log for the release workflow can be seen [here](https://github.com/lightninglabs/taproot-assets/actions/runs/20023049477/job/57414058452), demonstrating that the image builds, and that the release artifacts are produced as expected.

File: .github/workflows/release.yaml (hunk 5 above)
Comment (jtobin) [reply .github/workflows/release.yaml:49]: I've since tested this and can confirm it works as expected. :+1:

(See [log](https://github.com/lightninglabs/taproot-assets/actions/runs/20023049477/job/57414058452)).

**Comment by litbot-9000** [comment]
@ffranr: review reminder
@jtobin, remember to re-request review from reviewers when ready
