### PR TITLE
taprpc: Set dec display when metadata is empty

### LINKED ISSUE #972: [bug]: Minting a normal asset with --decimal_display does not yield expected results
### Background

I minted a new asset with the flag: `--decimal-display 3` but the created asset shows `"decimal_display":  0`

### Your environment

`litd integrated mode`
branch: `0-19-staging`
commit: `fa32097a4d0deee7e84872690194d18f108cf5a5`

### Steps to reproduce

Command used:

`tapcli --tlscertpath ~/.lit/tls.cert --rpcserver=localhost:8443 --network=testnet assets mint --type normal --name beefbux --supply 1000000 --decimal_display 3 --new_grouped_asset --meta_type json`

`tapcli assets mint finalize`

### Expected behavior

When running `tapcli assets list`, I expect to see the asset with its defined decimal display.

### Actual behavior

The minted asset appears to have its decimal display set to 0:

```
        {
            "version":  "ASSET_VERSION_V0",
            "asset_genesis":  {
                "genesis_point":  "1fd2b57bbbaaae90d9015f7ea4b75413629aeb591fc789ad42c900d5a999f56a:1",
                "name":  "beefbux",
                "meta_hash":  "0000000000000000000000000000000000000000000000000000000000000000",
                "asset_id":  "9052f8837a836ee5d48b8609f78cb475aec480d2e58fe798b0d5b8354245e121",
                "asset_type":  "NORMAL",
                "output_index":  0
            },
            "amount":  "1000000",
            "lock_time":  0,
            "relative_lock_time":  0,
            "script_version":  0,
            "script_key":  "02c71287f4763bc86e7144933d586e534ea799b6530dd49909d78e7eb1c00baaa7",
            "script_key_is_local":  true,
            "asset_group":  {
                "raw_group_key":  "029b811d7ef954704bf07c949f0464b680224a808468fd13d391c9141d9046459c",
                "tweaked_group_key":  "02e446b1ee2e362a75fa94f2ed02a2653df979225d8d68c79ae0643e7fcb317f64",
                "asset_witness":  "0140fd75b9eb5b1840b426eb1b3248f0038e8d38665c12bab4e7817322d517eef6ab86675433edf171e7e9bfb52315d20265b40e4ab28638cd2388212e68bc656032",
                "tapscript_root":  ""
            },
            "chain_anchor":  {
                "anchor_tx":  "020000000001016af599a9d500c942ad89c71f59eb9a621354b7a47e5f01d990aeaabb7bb5d21f01000000000000000002e80300000000000022512082bcb8523d1c7ecf7a156c452df083144ffd7d0691f0c5314f5c1586476343a4704b0a02000000002251209423066211c876f9ba1709678567091e9c750747747625b2c4725a68944a4d5301408391f5c0f3d4873c48d83d20bb9749b2f709f0dff5e6b37df995f81372e73d926d3d80c73bb25dd66d35c36922a5c180bc824730224ff369869f397c3110d98900000000",
                "anchor_block_hash":  "0000000000000000000000000000000000000000000000000000000000000000",
                "anchor_outpoint":  "f939a83cf71a7d8d743a989e81ad9c292f4e6c4f7c3bc5639313cd1739a15363:0",
                "internal_key":  "03b7484d5f0c6102cb58c016186fe28f8e7bc007c6d859eaa3b206534098e3c14d",
                "merkle_root":  "a376b5e1cd538fd5c4c1426bda4621d02c5c0924c5ff689dcc59712efc291255",
                "tapscript_sibling":  "",
                "block_height":  0
            },
            "prev_witnesses":  [],
            "is_spent":  false,
            "lease_owner":  "",
            "lease_expiry":  "0",
            "is_burn":  false,
            "script_key_declared_known":  false,
            "script_key_has_script_path":  false,
            "decimal_display":  {
                "decimal_display":  0
            }
        }
```

Maybe unrelated, but I also don't understand why the block height appears to be zero (and the block hash is empty). The minting transaction had over 2000 confirmations at the time when I pulled the above data: [f939a83cf71a7d8d743a989e81ad9c292f4e6c4f7c3bc5639313cd1739a15363](https://mempool.space/testnet/tx/f939a83cf71a7d8d743a989e81ad9c292f4e6c4f7c3bc5639313cd1739a15363)

### PR DESCRIPTION
**Pull request by jharveyb**
Resolves #972 by setting the dec display as the only JSON object when the given metadata is empty. The RPC request that causes this behavior is tested in the meta itest, and I manually tested the CLI for:

- Non-zero dec display, empty metadata, JSON meta type -> correct `taprpc.AssetMeta` struct is passed to the RPC, asset listed correctly after minting (this was with the exact CLI cmd Leo posted).
- zero dec display, empty metadata, JSON meta type -> rejected for empty metadata
- unknown meta type, empty metadata -> rejected for empty metadata (IIUC this was the existing behavior)

### CODE REVIEW

**Review by Roasbeef — APPROVED** [review]
LGTM 👍

File: cmd/tapcli/assets.go [hunk 1]
```diff
@@ -304,12 +323,10 @@ func mintAsset(ctx *cli.Context) error {
...
-			AssetType: assetType,
-			Name:      ctx.String(assetTagName),
-			AssetMeta: assetMeta,
-			DecimalDisplay: uint32(
-				ctx.Uint64(assetDecimalDisplayName),
-			),
+			AssetType:       assetType,
+			Name:            ctx.String(assetTagName),
+			AssetMeta:       assetMeta,
+			DecimalDisplay:  uint32(decDisplay),
```
Comment (Roasbeef) [inline cmd/tapcli/assets.go:329]: Based on this comment, I think we need another check above to assume that if decimal display is set, then we're using a JSON meta type.

**Review by Roasbeef — CHANGES_REQUESTED** [review]

File: cmd/tapcli/assets.go (hunk 1 above)
Comment (Roasbeef) [reply cmd/tapcli/assets.go:329]: Or we just update in the docs that decimal display requires the json meta data type?
