### PR TITLE
authmailbox: wait for multiSub reconnect in restart test

### LINKED ISSUE #2089: [flake]: TestServerClientAuthAndRestart flake
This test was observed failing flakily in CI in [this job](https://github.com/lightninglabs/taproot-assets/actions/runs/24731239736/job/72444495168). Similar, but not quite the same, as the flake fixed in #2072.

### PR DESCRIPTION
**Pull request by jtobin**
Resolves #2089.

TestServerClientAuthAndRestart published msg2 after waiting for client1 and client2 to reconnect, but did not wait for the MultiSubscription's underlying subscriptions.  Under -race the multiSub could still be mid-handshake when publishMessage fired, silently dropping the message and causing the readMultiSub timeout.

Add AllSubscribed() to MultiSubscription so callers can poll readiness, and use it in the test after server restart.

### CODE REVIEW

File: authmailbox/multi_subscription.go [hunk 1]
```diff
@@ -123,6 +123,23 @@ func (m *MultiSubscription) Subscribe(ctx context.Context, serverURL url.URL,
...
+	for _, client := range m.clients {
+		for _, sub := range client.subscriptions {
+			if !sub.IsSubscribed() {
+				return false
+			}
+		}
+	}
+
+	return true
+}
```
[the remark this answers is not in the document]
Comment (jtobin) [reply authmailbox/multi_subscription.go]: This doesn't pose an issue in the sole test in which the helper is used; I argue not worth fixing for speculative defensiveness.

**Review by GeorgeTsagk — APPROVED** [review]
LGTM

**Review by darioAnongba — APPROVED** [review]

File: authmailbox/multi_subscription.go [hunk 2]
```diff
@@ -123,6 +123,23 @@ func (m *MultiSubscription) Subscribe(ctx context.Context, serverURL url.URL,
 	return nil
 }
 
+// AllSubscribed returns true if every subscription across all clients
+// is currently connected and authenticated.
+func (m *MultiSubscription) AllSubscribed() bool {
```
Comment (darioAnongba) [inline authmailbox/multi_subscription.go]: is this only used in tests? We shouldn't create functions in the `struct` to help in tests. If this is a test helper, then it should accept a subscription and do the check externally?

**Review by darioAnongba — APPROVED** [review]

File: authmailbox/multi_subscription.go (hunk 2 above)
Comment (jtobin) [reply authmailbox/multi_subscription.go]: Fixed in updated changeset.
