### PR TITLE
Fee bumping when fee estimation doesn't meet min relay fee

### LINKED ISSUE #1171: [bug]: On signet, min-relay-fee is not met if fee is not specified. Fee will be 1 sat short
### Background

When using signet, it seems that calls to AnchorVirtualPSBT RPC and to SendAsset RPC will result in a transaction that does not meet the min-relay-fee. The vsize of the transaction ends up being 254.5 vB usually (see https://mempool.space/signet/tx/aff4e70f1816ec611da03a89889be79b81b57067355abe99c14e89f0f2085ba8#vin=0 as an example). 

Here is an example txn that will not relay with a fee rate of **barely** under 1.00 sats/vB (size is 254.5, fee is 254)

```
02000000000102aee61b60b329cd99950230a146a11b16ff53c85109d352aee5a5e87088f62b990000000000000000000c6c3c8409df4c95942069945a9cd867d657d13b635814d7884580d9c74a64be01000000000000000003e803000000000000225120b5b88d39d530a564e1b6e2b714e0d4c16bc284b49778898f98faffd8db135b13e803000000000000225120b59492b62792ca980cd5dd087099897d63b6f85fea0680a43e792d70191ee54d00b5eb0b00000000225120d430711c2a954904278394c6c9378713534a2d1d5c37fbea58deebef95596cea0140510398932e106f72156dc13213a7999ef77544a8bf5ee11b7b24859555908b8bd18b30c5889233c95abcc4f7cd2dddc2eab36266f89c38adb137c6e6bdda3a960140a2ccf5834b81952fe1c3eac8276743d6c4571ba232cc98ea0129e7b3582cca21dab09f0f953b98e5f0f8768ec0a4fd400a6b36cc496cb96cef7c47ba75fde17300000000
```

I'm not sure exactly the problem here, perhaps something related to the nature of signet transactions (I havent seen this problem on other networks). Also unfortunately it seems not everyone has adopted package relay, so unable to use CPFP via package relay to unstuck the above txn using the below child:
```
02000000000101f18d47aae097b364ad0dc9409c8b917db47cf1f1535606283614b943d84ed4c202000000000000000001a784eb0b0000000022512044be1fcf86a056efc21c6775b3b348756f3e099a3da70bbe5726558db2b595ac0140b16fcf7770feb3190b6a1bc524c3f80244e7d09399e66808a91594b16289d2b25d341e597834fc7622dc5857576c1a3d72592fce3105636cd5b7a2aad3438e597f5d0300
```

### Your environment

```sh
tapcli getinfo                       # version of `tapd`, `lnd`, and network
{
    "version": "0.4.1-alpha commit=622c7929",
    "lnd_version": "0.18.3-beta",
    "network": "signet",
    "lnd_identity_pubkey": "026580b3316c7b10f487235d8e3247ba960f4d96952aa0edb85a4e096501bb4acc",
    "node_alias": "Tajfi",
    "block_height": 220574,
    "block_hash": "00000109ab0a6ba26dd8b8fb078368e5af4d8ad6fbaca796933d1d1cc4ab6a82",
    "sync_to_chain": true
}
uname -mrsv                          # operating system 
Linux 6.8.0-1015-gcp #17~22.04.1-Ubuntu SMP Tue Sep  3 16:11:52 UTC 2024 x86_64

bitcoind --version  # version of `btcd`, `bitcoind`, or other backend
Bitcoin Core version v28.0.0
```

### Steps to reproduce

Mint any asset and finalize the batch. Then try to spend the asset using the CLI and do NOT specify a fee rate.

### Expected behavior

Transaction should be generated with 254.5 sats --> round up to 255 sats

### Actual behavior

Transaction generated is 254 sats

### PR DESCRIPTION
**Pull request by gijswijs**
Both the minting transaction and normal on chain transactions suffer from edge cases where the fee estimation comes up with a fee that doesn't meet the current min relay fee. This PR changes that behavior by checking the estimated fee against the min relay fee, and bumps the fee if it doesn't clear the minimum fee height implied by min relay fee.

fixes #1171

### CODE REVIEW

**Comment by dstadulis** [comment]
itest failing due to feeEstimation changes
some values aren't reset -- will investigate more

File: tapgarden/planter.go [hunk 1]
```diff
@@ -566,6 +566,17 @@ func (c *ChainPlanter) fundGenesisPsbt(ctx context.Context,
 			return nil, fmt.Errorf("unable to estimate fee: %w",
 				err)
 		}
+		minRelayFee, err := c.cfg.Wallet.MinRelayFee(ctx)
+		if err != nil {
+			return nil, fmt.Errorf("unable to obtain minimum relay"+
```
Comment (guggero) [inline tapgarden/planter.go:571]: nit: for ease of review, we standardize putting the space between words on the previous line if we have to wrap a string.

**Review by guggero — APPROVED** [review]
Very nice, LGTM :tada:

File: tapgarden/planter.go [hunk 2]
```diff
@@ -566,6 +566,17 @@ func (c *ChainPlanter) fundGenesisPsbt(ctx context.Context,
 			return nil, fmt.Errorf("unable to estimate fee: %w",
 				err)
 		}
+		minRelayFee, err := c.cfg.Wallet.MinRelayFee(ctx)
```
Comment (jharveyb) [inline tapgarden/planter.go:569]: As-is this won't catch the case of the user manually specifying a feerate below minrelayfee.

Also, in that case IMO you'd want to fail with an error message reporting the minrelayfee, instead of bumping the fee silently.

So I'd suggest moving this check after the switch instead of in the default case; then you can switch behavior based on `manualFeeRate != nil`.

File: tapfreighter/chain_porter.go [hunk 3]
```diff
@@ -1128,6 +1128,17 @@ func (p *ChainPorter) stateStep(currentPkg sendPackage) (*sendPackage, error) {
 				return nil, fmt.Errorf("unable to estimate "+
 					"fee: %w", err)
 			}
+			minRelayFee, err := p.cfg.Wallet.MinRelayFee(ctx)
```
Comment (jharveyb) [inline tapfreighter/chain_porter.go:1131]: Same note re: separate switch to catch manual feerate.

File: itest/send_test.go [hunk 4]
```diff
@@ -129,6 +133,123 @@ func testBasicSendUnidirectional(t *harnessTest) {
...
+	// be returned by the fee estimation.
+	lowFeeRate := chainfee.SatPerVByte(1).FeePerKWeight()
+	highMinRelayFeeRate := chainfee.SatPerVByte(2).FeePerKVByte()
+	defaultMinRelayFeeRate := chainfee.SatPerVByte(1).FeePerKVByte()
+	defaultFeeRate := chainfee.SatPerKWeight(3125)
+	t.lndHarness.SetFeeEstimateWithConf(lowFeeRate, 6)
+	t.lndHarness.SetMinRelayFeerate(highMinRelayFeeRate)
+
+	// Reset all fee rates to their default value at the end of this test.
+	defer t.lndHarness.SetMinRelayFeerate(defaultMinRelayFeeRate)
```
Comment (jharveyb) [inline itest/send_test.go:178]: 👍🏽 

good pattern re: defer!

File: itest/send_test.go [hunk 5]
```diff
@@ -129,6 +133,123 @@ func testBasicSendUnidirectional(t *harnessTest) {
...
+	)
+
+	AssertNonInteractiveRecvComplete(t.t, secondTapd, 1)
+	AssertSendEventsComplete(t.t, bobAddr.ScriptKey, sendEvents)
+
+	// Close event stream.
+	err = events.CloseSend()
+	require.NoError(t.t, err)
+
+	wg.Wait()
```
Comment (jharveyb) [inline itest/send_test.go:250]: `wg` not used in this test?

**Review by jharveyb — COMMENTED** [review]
Looks close! Just one note: re handling manual feerates.

The itest can be expanded a bit to check for failure on an insufficient manual feerate for both mint and transfer as well.

File: tapgarden/planter.go (hunk 2 above)
Comment (gijswijs) [reply tapgarden/planter.go:569]: Correct. The issue was raised specifically in a scenario where the user did *not* specify a feerate. The reasoning for putting the check inside the switch was that if you do specify the feerate manually, you are fully responsible for it. You could *even* specify a feerate below minrelayfee.

**Comment by gijswijs** [comment]
> The itest can be expanded a bit

Famous last words. :smile: 

Anyways, I've changed both `sendAssetsToAddr` and `MintAssetsConfirmBatch` to be able to test with specific feerates and to be able to test for specific errors. I hope we can benefit from this more granular control in the future for other itests as well.

Please also have a look at 

https://github.com/lightninglabs/taproot-assets/blob/1159a3fe2911b0dc4d5e1f7816daa8d560da58bc/rpcserver.go#L685-L686

If I'm right we could remove a check there.

File: rpcserver.go [hunk 6]
```diff
@@ -664,8 +664,13 @@ func (r *rpcServer) MintAsset(ctx context.Context,
 
 // checkFeeRateSanity ensures that the provided fee rate, in sat/kw, is above
 // the same minimum fee used as a floor in the fee estimator.
-func checkFeeRateSanity(rpcFeeRate uint32) (*chainfee.SatPerKWeight, error) {
+func checkFeeRateSanity(ctx context.Context, rpcFeeRate uint32,
+	lndWallet lndclient.WalletKitClient) (*chainfee.SatPerKWeight, error) {
 	feeFloor := uint32(chainfee.FeePerKwFloor)
```
Comment (guggero) [inline rpcserver.go:669]: nit: need empty line after multi-line function call definition.

File: rpcserver.go [hunk 7]
```diff
@@ -676,17 +681,27 @@ func checkFeeRateSanity(rpcFeeRate uint32) (*chainfee.SatPerKWeight, error) {
 		return nil, fmt.Errorf("manual fee rate below floor: "+
 			"(fee_rate=%d, floor=%d sat/kw)", rpcFeeRate, feeFloor)
 
+	// A manual fee was set but is below minRelayFee.
+	// TODO (gijs):  Can minRelayFee ever be lower than feeFloor? If not, we
```
Comment (guggero) [inline rpcserver.go:685]: No, that would be a mistake. I can't speak for all backend implementations, whether they would respect that. But if we want to be sure, we'd check `minRelayFee` returned from lnd (which is just passed forward from the chain backend) and check it against the fee flow. If it's below, we just use the fee floor.

File: tapgarden/planter.go [hunk 8]
```diff
@@ -571,6 +571,32 @@ func (c *ChainPlanter) fundGenesisPsbt(ctx context.Context,
...
+		// If a fee rate was manually assigned for this batch, we err
+		// out, otherwise we silently bump the feerate.
+		case manualFeeRate != nil:
+			// This case should already be handled by the
+			// `checkFeeRateSanity` of `rpcserver.go`. We check here
+			// again to be safe.
+			return nil, fmt.Errorf("feerate does not meet " +
+				"minrelayfee")
+		default:
+			log.Infof("bump fee rate for batch %x to meet "+
```
Comment (guggero) [inline tapgarden/planter.go:592]: nit: Log statements usually start capitalized (vs. error messages that should be lower case according to Golang defaults and linter preferences).

File: itest/addrs_test.go [hunk 9]
```diff
@@ -1078,24 +1078,70 @@ func sendProofUniRPC(t *harnessTest, src, dst *tapdHarness, scriptKey []byte,
 	return importResp
 }
 
-// sendAssetsToAddr spends the given input asset and sends the amount specified
+// sendOptions is a struct that holds a SendAssetRequest and an
+// optional error string that should be tested against.
+type sendOptions struct {
```
Comment (guggero) [inline itest/addrs_test.go:1083]: Nice :+1:

File: itest/addrs_test.go [hunk 10]
```diff
@@ -1078,24 +1078,70 @@ func sendProofUniRPC(t *harnessTest, src, dst *tapdHarness, scriptKey []byte,
...
-	for i, addr := range receiverAddrs {
-		encodedAddrs[i] = addr.Encoded
+	// Apply all the functional options
+	for _, opt := range opts {
+		opt(options)
 	}
 
+	require.NotEmpty(t.t, options.sendAssetRequest.TapAddrs)
+
+	// We need the first address's scriptkey to subscribe to events
```
Comment (guggero) [inline itest/addrs_test.go:1138]: nit: missing full stop at end of sentence.

**Review by guggero — APPROVED** [review]
Nice, LGTM :tada:

File: itest/addrs_test.go (hunk 10 above)
Comment (gijswijs) [reply itest/addrs_test.go:1138]: Fun fact: This came from Claude LLM.

File: rpcserver.go (hunk 7 above)
Comment (gijswijs) [reply rpcserver.go:685]: Resolved it slightly different, so that we can still throw different errors.

File: tapfreighter/chain_porter.go [hunk 11]
```diff
@@ -1128,6 +1128,40 @@ func (p *ChainPorter) stateStep(currentPkg sendPackage) (*sendPackage, error) {
...
+			switch {
+			// If a fee rate was manually assigned for this parcel,
+			// we err out, otherwise we silently bump the feerate.
+			case addrParcel.transferFeeRate != nil:
+				// This case should already be handled by the
+				// `checkFeeRateSanity` of `rpcserver.go`. We
+				// check here again to be safe.
+				p.unlockInputs(ctx, &currentPkg)
+
+				return nil, fmt.Errorf("feerate does not " +
```
Comment (jharveyb) [inline tapfreighter/chain_porter.go:1156]: super-nit: should return the `minrelayfee` here so the user can reattempt above that feerate.

File: tapgarden/planter.go [hunk 12]
```diff
@@ -571,6 +571,32 @@ func (c *ChainPlanter) fundGenesisPsbt(ctx context.Context,
...
+	// bump it up.
+	if feeRate < minRelayFee {
+		switch {
+		// If a fee rate was manually assigned for this batch, we err
+		// out, otherwise we silently bump the feerate.
+		case manualFeeRate != nil:
+			// This case should already be handled by the
+			// `checkFeeRateSanity` of `rpcserver.go`. We check here
+			// again to be safe.
+			return nil, fmt.Errorf("feerate does not meet " +
```
Comment (jharveyb) [inline tapgarden/planter.go:589]: same nit re: displaying `minrelayfee`.

**Review by jharveyb — APPROVED** [review]
Great changes + nice to see itest improvements 🎉
