### PR TITLE
 chain_bridge+fn: add retry logic for RPC calls to improve reliability in load-balanced environments

### LINKED ISSUE #1562: [bug]: Mint Not Showing as Confirmed Despite 6+ confirmations
### Background

We've had 2 reports of mint transactions having 6+ on-chain confirmations, but not being recognized as confirmed by the tapd daemon.  

### Your environment

Both are on the latest, non-rc, version of litd (v14.1) running in integrated mode with btcd backend. One instance occurred in testnet and one instance occurred in mainnet. 

### Steps to reproduce

Unknown at this stage. 

### Expected behavior

Once a mint transaction is confirmed on-chain, it should show up as confirmed within the tapd daemon for `tapcli assets list`

### Actual behavior

*Instance 1: Testnet* 
 Minted some assets on testnet. The onchain transactions have many confirmations, however when I do tapcli assets list it shows them both as unconfirmed. Why is that?
```
    "assets":  [],
    "unconfirmed_transfers":  "0",
    "unconfirmed_mints":  "2" 
```

I minted an asset with `--new_grouped_asset` , finalized it and this worked. It created an onchain transaction.
I think immediately tried to mint another asset by specifying the group key created in this first mint. It failed because I had no available UTXOs for minting which makes sense. 
This batch switched to 
```
BATCH_STATE_FROZEN  error messsage:
[tapcli] unable to finalize batch: rpc error: code = Unknown desc = unable to finalize batch: unable to finalize minting batch: unable to fund minting PSBT for batch: 0225a910dd5be980022b7ec39bd8118581d052985f4b562dc6311d0cdf5b3f93fb unable to fund psbt: unable to fund psbt: rpc error: code = Unknown desc = error selecting coins: not enough witness outputs to create funding transaction, need 0.00001000 BTC only have 0 BTC available
```

I waited for the first mint to get confirmed and then once it was confirmed I minted a second asset with the group key no problem. This worked and published just fine. So at this point we have 2 Batches with `BATCH_STATE_BROADCAST` and one with `BATCH_STATE_FROZEN`.

Even after many onchain confirmations, the 2 successful batches never moved to `BATCH_STATE_FINALIZED`. I only had 2 unconfirmed mints. I restarted the node to try to get it to kick in. After a restart, that Frozen batch actually got broadcasted (which was unexpected) and confirmed. That batch now shows as `BATCH_STATE_FINALIZED` , but the two successful ones are still at `BATCH_STATE_BROADCAST` . I don’t understand why.
Additionally I see this in my logs:
```
[WRN] UNIV: Cannot push proof via logged server push: cannot push proof to remote server(testnet.universe.lightning.finance:10029): cannot push proof to remote server(testnet.universe.lightning.finance:10029): rpc error: code = Unknown desc = unable to verify proof: unable to verify proof (issuance-f538d95ef3dc5e750275e7ea3f2c1af3342d024ba4b9ed230365ce0ed14620e5 (asset_id=0000000000000000000000000000000000000000000000000000000000000000, group_key=3127efed588df7cac5e5d8df2e6a1f1b88a07f742ed4bffb2bb923f3bf922c2e, proof_type=issuance), outpoint=60723e7fe5d2e4be3b12f737343aecc087b8babcba0a74937e6c562f6fbf360b:0, scriptKey=027d21392ac9c0421517355bc119ead8c9f072be156334777d9cde79f7e77af8b1): group key not known: 023127efed588df7cac5e5d8df2e6a1f1b88a07f742ed4bffb2bb923f3bf922c2e: group verifier: no matching asset group: sql: no rows in result set: group key not known
```

Tried again with a brand new node and only 1 batch. It is still stuck at `BATCH_STATE_BROADCAST` even with many confirmations. Here are logs for the second attempt (second node): 

```
2025-05-08 10:54:41	
2025-05-08 15:54:41.382 [INF] UNIV: Attempting to sync universe: host=testnet.universe.lightning.finance:10029, sync_type=full, ids=([]universe.Identifier) <nil>
2025-05-08 10:54:41	
2025-05-08 15:54:41.382 [INF] UNIV: Syncing Universe state with server=testnet.universe.lightning.finance:10029
2025-05-08 10:54:41	
2025-05-08 15:54:41.382 [INF] UNIV: Synchronizing with 1 federation members
2025-05-08 10:54:28	
2025-05-08 15:54:28.389 [INF] LNWL: Marking unconfirmed transaction ac6cf8ada16e0d6c7eabef767713a1f033609a6a6c47da89b0ebf2f18e239021 mined in block 4325420
2025-05-08 10:54:27	
2025-05-08 15:54:27.078 [INF] GRPH: Block 00000000009f47287a9cad804392b1b6d0717944167c4607d16e051d65810068 (height=4325420) closed 0 channels
2025-05-08 10:54:27	
2025-05-08 15:54:27.070 [INF] GRPH: Pruning channel graph using block 00000000009f47287a9cad804392b1b6d0717944167c4607d16e051d65810068 (height=4325420)
2025-05-08 10:54:27	
2025-05-08 15:54:27.028 [ERR] GRDN: unable to advance state machine: unable to construct minting proofs: invalid proof file generated: failed to validate proof block header: unable to retrieve block hash: rpc error: code = Unknown desc = -1: Block number out of range
2025-05-08 10:54:27	
2025-05-08 15:54:27.028 [ERR] RPCS: [/chainrpc.ChainKit/GetBlockHash]: -1: Block number out of range
2025-05-08 10:54:27	
2025-05-08 15:54:27.021 [INF] GRDN: BatchCaretaker(037ffbe2ee1316dd27f1873ec3426d7748046e1427f1b32a47925bd4188251043b), advancing from state=BatchStateConfirmed to state=BatchStateFinalized
2025-05-08 10:54:27	
2025-05-08 15:54:27.021 [INF] GRDN: MintingBatch(037ffbe2ee1316dd27f1873ec3426d7748046e1427f1b32a47925bd4188251043b): confirmed at block(hash=00000000009f47287a9cad804392b1b6d0717944167c4607d16e051d65810068, height=4325420)
2025-05-08 10:54:27	
2025-05-08 15:54:27.008 [INF] GRDN: New block at height 4325420
2025-05-08 10:54:27	
2025-05-08 15:54:27.008 [INF] RPCS: Received new block notification: height=4325420
2025-05-08 10:54:27	
2025-05-08 15:54:27.008 [INF] UTXN: Attempting to graduate height=4325420: num_kids=0, num_babies=0
2025-05-08 10:54:27	
2025-05-08 15:54:27.008 [INF] LNWL: Web API returning 1012 sat/kvb for min relay feerate
2025-05-08 10:54:27	
2025-05-08 15:54:27.007 [INF] NTFN: New block: height=4325420, sha=00000000009f47287a9cad804392b1b6d0717944167c4607d16e051d65810068
2025-05-08 10:54:13	
2025-05-08 15:54:13.717 [INF] GRPH: Processed channels=0 updates=0 nodes=6 in last 2m30.002032922s
2025-05-08 10:50:43	
2025-05-08 15:50:43.715 [INF] GRPH: Processed channels=0 updates=0 nodes=2 in last 59.999667454s
2025-05-08 10:49:43	
2025-05-08 15:49:43.715 [INF] GRPH: Processed channels=0 updates=2 nodes=2 in last 1m0.000801406s
2025-05-08 10:49:38	
2025-05-08 15:49:38.732 [INF] NTFN: New confirmation subscription: conf_id=2, txid=ac6cf8ada16e0d6c7eabef767713a1f033609a6a6c47da89b0ebf2f18e239021, num_confs=1 height_hint=4325419
2025-05-08 10:49:38	
2025-05-08 15:49:38.731 [INF] GRDN: BatchCaretaker(037ffbe2ee1316dd27f1873ec3426d7748046e1427f1b32a47925bd4188251043b): transition states: BatchStateBroadcast -> BatchStateBroadcast
2025-05-08 10:49:38	
2025-05-08 15:49:38.731 [INF] NTFN: New confirmation subscription: conf_id=1, txid=ac6cf8ada16e0d6c7eabef767713a1f033609a6a6c47da89b0ebf2f18e239021, num_confs=6 height_hint=4325419
2025-05-08 10:49:38	
2025-05-08 15:49:38.730 [INF] LNWL: ac6cf8ada16e0d6c7eabef767713a1f033609a6a6c47da89b0ebf2f18e239021: tx already in mempool
2025-05-08 10:49:38	
2025-05-08 15:49:38.720 [WRN] BTWL: Transaction ac6cf8ada16e0d6c7eabef767713a1f033609a6a6c47da89b0ebf2f18e239021 not accepted by mempool: already have transaction in mempool ac6cf8ada16e0d6c7eabef767713a1f033609a6a6c47da89b0ebf2f18e239021
2025-05-08 10:49:38	
2025-05-08 15:49:38.719 [INF] LNWL: Inserting unconfirmed transaction ac6cf8ada16e0d6c7eabef767713a1f033609a6a6c47da89b0ebf2f18e239021
2025-05-08 10:49:38	
2025-05-08 15:49:38.716 [INF] GRDN: BatchCaretaker(037ffbe2ee1316dd27f1873ec3426d7748046e1427f1b32a47925bd4188251043b): extracted finalized GenesisTx
2025-05-08 10:49:38	
2025-05-08 15:49:38.716 [INF] GRDN: BatchCaretaker(037ffbe2ee1316dd27f1873ec3426d7748046e1427f1b32a47925bd4188251043b): transition states: BatchStateCommitted -> BatchStateBroadcast
2025-05-08 10:49:38	
2025-05-08 15:49:38.714 [INF] LNWL: Imported address tb1pdtj6jqm50p0pv9vstgw8kd25zum3xgk7m259hk3w5jr5q27de8vq285gdv
2025-05-08 10:49:38	
2025-05-08 15:49:38.707 [INF] GRDN: BatchCaretaker(037ffbe2ee1316dd27f1873ec3426d7748046e1427f1b32a47925bd4188251043b): GenesisPacket finalized (absolute_fee_sats: 770)
2025-05-08 10:49:38	
2025-05-08 15:49:38.703 [INF] GRDN: BatchCaretaker(037ffbe2ee1316dd27f1873ec3426d7748046e1427f1b32a47925bd4188251043b): finalizing GenesisPacket
2025-05-08 10:49:38	
2025-05-08 15:49:38.703 [INF] GRDN: BatchCaretaker(037ffbe2ee1316dd27f1873ec3426d7748046e1427f1b32a47925bd4188251043b): transition states: BatchStateFrozen -> BatchStateCommitted
2025-05-08 10:49:38	
2025-05-08 15:49:38.697 [INF] GRDN: BatchCaretaker(037ffbe2ee1316dd27f1873ec3426d7748046e1427f1b32a47925bd4188251043b): committing sprouts to disk
2025-05-08 10:49:38	
2025-05-08 15:49:38.696 [INF] GRDN: BatchCaretaker(037ffbe2ee1316dd27f1873ec3426d7748046e1427f1b32a47925bd4188251043b): mapping 1 seedlings to asset sprouts, with genesis_point=bd47d017443255d4ca53d9f6f5a2923ef3a1ca03e2521ce31bc9e721db80e747:1
2025-05-08 10:49:38	
2025-05-08 15:49:38.696 [INF] GRDN: BatchCaretaker(037ffbe2ee1316dd27f1873ec3426d7748046e1427f1b32a47925bd4188251043b), advancing from state=BatchStateFrozen to state=BatchStateBroadcast
2025-05-08 10:49:38	
2025-05-08 15:49:38.681 [INF] GRDN: Funded GenesisPacket for batch: 037ffbe2ee1316dd27f1873ec3426d7748046e1427f1b32a47925bd4188251043b
2025-05-08 10:49:38	
2025-05-08 15:49:38.666 [INF] LNWL: Web API returning 1012 sat/kvb for min relay feerate
2025-05-08 10:49:38	
2025-05-08 15:49:38.666 [WRN] LNWL: Web API does not have a fee rate for target=6, using the fee rate for target=2 instead
2025-05-08 10:49:38	
2025-05-08 15:49:38.666 [INF] GRDN: estimated fee rate for batch: 037ffbe2ee1316dd27f1873ec3426d7748046e1427f1b32a47925bd4188251043b, 4236 sat/kvb
2025-05-08 10:49:38	
2025-05-08 15:49:38.665 [INF] LNWL: Web API returning 1012 sat/kvb for min relay feerate
2025-05-08 10:49:38	
2025-05-08 15:49:38.665 [WRN] LNWL: Web API does not have a fee rate for target=6, using the fee rate for target=2 instead
2025-05-08 10:49:38	
2025-05-08 15:49:38.665 [INF] GRDN: creating skeleton PSBT for batch: 037ffbe2ee1316dd27f1873ec3426d7748046e1427f1b32a47925bd4188251043b
2025-05-08 10:49:38	
2025-05-08 15:49:38.665 [INF] GRDN: Attempting to fund batch: 037ffbe2ee1316dd27f1873ec3426d7748046e1427f1b32a47925bd4188251043b
2025-05-08 10:49:38	
2025-05-08 15:49:38.661 [INF] GRDN: Freezing MintingBatch(key=037ffbe2ee1316dd27f1873ec3426d7748046e1427f1b32a47925bd4188251043b, num_assets=1)
2025-05-08 10:49:38	
2025-05-08 15:49:38.661 [INF] GRDN: Finalizing batch 037ffbe2ee1316dd27f1873ec3426d7748046e1427f1b32a47925bd4188251043b
2025-05-08 10:49:38	
2025-05-08 15:49:38.661 [INF] LNWL: Web API returning 1012 sat/kvb for min relay feerate
2025-05-08 10:49:38	
2025-05-08 15:49:38.661 [WRN] LNWL: Web API does not have a fee rate for target=6, using the fee rate for target=2 instead
2025-05-08 10:49:38	
2025-05-08 15:49:38.656 [INF] LITD: Handling gRPC request: /mintrpc.Mint/FinalizeBatch
2025-05-08 10:49:22	
2025-05-08 15:49:22.866 [INF] GRDN: Request for new seedling: AssetSeedling(name=x45d, type=Normal, amt=50000, version=0) received
2025-05-08 10:49:22	
2025-05-08 15:49:22.859 [INF] GRDN: Adding AssetSeedling(name=x45d, type=Normal, amt=50000, version=0) received to new MintingBatch
2025-05-08 10:49:22	
2025-05-08 15:49:22.848 [INF] GRDN: Creating new MintingBatch
2025-05-08 10:49:22	
2025-05-08 15:49:22.830 [INF] RPCS: [MintAsset]: version=0, type=Normal, name=x45d, amt=50000, enable_emission=true
```

*Instance 2: Mainnet* 

`tapcli assets list` is showing:
  
```  
"unconfirmed_transfers":  "2",
    "unconfirmed_mints":  "1"
```
however the mint I performed >6 confirmations. Also in that output I can see the genesis info of that new asset, however the  chain_anchor.block_height has a value of 0 seemingly indicating it does not recognize being confirmed. When I do tapcli universe roots  this new asset does not show up. Restarting the node did not seem to kick it into place.

It appears logs run into this same `block number out of range` log

```
2025-05-20 10:49:45	
2025-05-20 15:49:45.462 [INF] LNWL: Marking unconfirmed transaction ec3ca4e9ad6bba0265eaf7aea1d8347d7f1817c088a372b27879bf15b1417f20 mined in block 897579
2025-05-20 10:49:45	
2025-05-20 15:49:45.461 [ERR] SWPR: Failed to handle bump event: transaction rejected: output already spent
2025-05-20 10:49:45	
2025-05-20 15:49:45.461 [ERR] SWPR: Fee bump attempt failed for tx=fdf4b555cc0769fc74d93c9b64cfe4e3f0a0efd52fc0e2a173bc2889e4e3c881: transaction rejected: output already spent
2025-05-20 10:49:45	
2025-05-20 15:49:45.461 [ERR] SWPR: Removing monitor record=5, tx=fdf4b555cc0769fc74d93c9b64cfe4e3f0a0efd52fc0e2a173bc2889e4e3c881, due to err: transaction rejected: output already spent
2025-05-20 10:49:45	
2025-05-20 15:49:45.461 [ERR] SWPR: Failed to publish tx fdf4b555cc0769fc74d93c9b64cfe4e3f0a0efd52fc0e2a173bc2889e4e3c881: transaction rejected: output already spent
2025-05-20 10:49:45	
2025-05-20 15:49:45.461 [INF] LNWL: Removed invalid transaction: fdf4b555cc0769fc74d93c9b64cfe4e3f0a0efd52fc0e2a173bc2889e4e3c881
2025-05-20 10:49:45	
2025-05-20 15:49:45.459 [INF] LNWL: fdf4b555cc0769fc74d93c9b64cfe4e3f0a0efd52fc0e2a173bc2889e4e3c881: broadcast failed because of: missing inputs
2025-05-20 10:49:45	
2025-05-20 15:49:45.406 [INF] LNWL: Marking unconfirmed transaction 3f7b30bbea3d75457f59417f430a129c1ad9835ada78ee8ce91a290b5d33bf16 mined in block 897579
2025-05-20 10:49:45	
2025-05-20 15:49:45.383 [WRN] BTWL: Transaction fdf4b555cc0769fc74d93c9b64cfe4e3f0a0efd52fc0e2a173bc2889e4e3c881 not accepted by mempool: already have transaction in mempool fdf4b555cc0769fc74d93c9b64cfe4e3f0a0efd52fc0e2a173bc2889e4e3c881
2025-05-20 10:49:45	
2025-05-20 15:49:45.382 [INF] LNWL: Inserting unconfirmed transaction fdf4b555cc0769fc74d93c9b64cfe4e3f0a0efd52fc0e2a173bc2889e4e3c881
2025-05-20 10:49:45	
2025-05-20 15:49:45.380 [INF] TCHN: Sweep request had no vPkts, exiting
2025-05-20 10:49:45	
2025-05-20 15:49:45.380 [INF] TCHN: Register broadcast of sweep_tx=(*wire.MsgTx)(0x4005f8bec0)({
2025-05-20 10:49:44	
2025-05-20 15:49:44.203 [ERR] GRDN: unable to advance state machine: unable to construct minting proofs: invalid proof file generated: failed to validate proof block header: unable to retrieve block hash: rpc error: code = Unknown desc = -1: Block number out of range
2025-05-20 10:49:44	
2025-05-20 15:49:44.203 [ERR] RPCS: [/chainrpc.ChainKit/GetBlockHash]: -1: Block number out of range
2025-05-20 10:49:44	
2025-05-20 15:49:44.196 [INF] GRDN: BatchCaretaker(022b49045d127a90e18e462f840448326668e294cc597a6ec6645e3d2a7a74c1d0), advancing from state=BatchStateConfirmed to state=BatchStateFinalized
2025-05-20 10:49:44	
2025-05-20 15:49:44.196 [INF] GRDN: MintingBatch(022b49045d127a90e18e462f840448326668e294cc597a6ec6645e3d2a7a74c1d0): confirmed at block(hash=00000000000000000001c38308acdd75b35cfcb41101967d9b776245630fe06c, height=897579)
2025-05-20 10:49:44	
2025-05-20 15:49:44.144 [INF] GRDN: New block at height 897579
2025-05-20 10:49:44	
2025-05-20 15:49:44.144 [INF] RPCS: Received new block notification: height=897579
2025-05-20 10:49:44	
2025-05-20 15:49:44.144 [INF] UTXN: Attempting to graduate height=897579: num_kids=0, num_babies=0
2025-05-20 10:49:44	
2025-05-20 15:49:44.144 [INF] LNWL: Web API returning 1012 sat/kvb for min relay feerate
2025-05-20 10:49:44	
2025-05-20 15:49:44.143 [INF] NTFN: New block: height=897579, sha=00000000000000000001c38308acdd75b35cfcb41101967d9b776245630fe06c
```

I went ahead and re-minted, but did not fee bump the mint this time, and it worked.

### PR DESCRIPTION
**Pull request by Roasbeef**
This PR fixes #1562 by implementing automatic retry logic with exponential backoff for all block and header fetching operations in the chain bridge.

Along the way, we introduce a generic `RetryFuncN` function in the `fn` package that wraps any fallible operation with configurable retry logic featuring:
  - Exponential backoff to avoid overwhelming the backend
  - Context cancellation support for clean shutdown
  - Configurable retry parameters (count, delays, backoff multiplier)

  The retry wrapper is then applied to all key RPC operations in `chain_bridge.go`:
  - `GetBlock` - Ensures we can always fetch full block data
  - `GetBlockHeader` - Ensures header retrieval succeeds
  - `GetBlockHash` - Ensures height-to-hash lookups work
  - `CurrentHeight` - Ensures chain tip queries succeed
  - `GetBlockTimestamp` - Ensures timestamp lookups work
  - `PublishTransaction` - Improves transaction broadcast reliability
  - `EstimateFee` - Ensures fee estimation succeeds

  With these changes, temporary inconsistencies or failures in load-balanced LND setups are automatically retried, ensuring that block and header fetching operations eventually succeed as long as at least one backend node is functional.

### CODE REVIEW

File: fn/retry.go [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+	// MaxBackoff caps the delay between retries to prevent excessive
+	// wait times.
+	MaxBackoff time.Duration
+}
+
+// DefaultRetryConfig provides sensible defaults for retrying RPC calls in
+// load-balanced environments where transient failures are expected.
+func DefaultRetryConfig() RetryConfig {
+	return RetryConfig{
+		MaxRetries:        3,
```
Comment (guggero) [inline fn/retry.go]: We probably need to tune these parameters a bit, or make them configurable by the user.
With these values, we won't even reach the max backoff (100ms->200ms->400ms, number of retries exhausted).

File: chain_bridge.go [hunk 2]
```diff
@@ -112,39 +113,57 @@ func (l *LndRpcChainBridge) RegisterBlockEpochNtfn(
...
-	if err != nil {
-		return nil, fmt.Errorf("unable to retrieve block: %w", err)
-	}
-
-	return block, nil
+	return fn.RetryFuncN(
+		ctx, fn.DefaultRetryConfig(), func() (*wire.MsgBlock, error) {
+			block, err := l.lnd.ChainKit.GetBlock(ctx, hash)
+			if err != nil {
+				return nil, fmt.Errorf(
```
Comment (guggero) [inline chain_bridge.go:122]: nit: can use the formatting exception for errors to save one line and visually distinguish better from normal function calls.

File: chain_bridge.go [hunk 3]
```diff
@@ -112,39 +113,57 @@ func (l *LndRpcChainBridge) RegisterBlockEpochNtfn(
...
 	hash chainhash.Hash) (*wire.MsgBlock, error) {
 
-	block, err := l.lnd.ChainKit.GetBlock(ctx, hash)
-	if err != nil {
-		return nil, fmt.Errorf("unable to retrieve block: %w", err)
-	}
-
-	return block, nil
+	return fn.RetryFuncN(
+		ctx, fn.DefaultRetryConfig(), func() (*wire.MsgBlock, error) {
```
Comment (guggero) [inline chain_bridge.go]: We could create the retry config in `NewLndRpcChainBridge` then re-use it here. Will get us one step closer to making it configurable by the user as well.

File: fn/retry.go (hunk 1 above)
Comment (GeorgeTsagk) [reply fn/retry.go]: yeah `7` (last wait time of 12.8sec) looks like a better pick, we wait for a total of 25sec after performing all backoffs

Comment (Roasbeef) [reply fn/retry.go]: > or make them configurable by the user.

Callers can pass in their own config fwiw. 

Updated to have a max retry of 10.

File: chain_bridge.go (hunk 2 above)
Comment (Roasbeef) [reply chain_bridge.go:122]: So I tried it, but the linter still went off. Maybe we only have this in `lnd`?

**Comment by guggero** [comment]
New unit test failed:
```
 --- FAIL: TestRetryFuncNBackoffIncreases (8.74s)
    retry_test.go:113: [rapid] flaky test, can not reproduce a failure
        To try to reproduce, specify -run="TestRetryFuncNBackoffIncreases" -rapid.failfile="testdata/rapid/TestRetryFuncNBackoffIncreases/TestRetryFuncNBackoffIncreases-20250606233039-12015.fail" (or -rapid.seed=12478158969883921579)
        Traceback (<nil>):
            <no error>
        Original traceback ((*T).FailNow() called):
            /home/runner/work/go/pkg/mod/pgregory.net/rapid@v1.2.0/engine.go:781 in pgregory.net/rapid.(*T).fail
            /home/runner/work/go/pkg/mod/pgregory.net/rapid@v1.2.0/engine.go:757 in pgregory.net/rapid.(*T).FailNow
            /home/runner/work/go/pkg/mod/github.com/stretchr/testify@v1.10.0/require/require.go:876 in github.com/stretchr/testify/require.InDelta
            /home/runner/work/taproot-assets/taproot-assets/fn/retry_test.go:157 in github.com/lightninglabs/taproot-assets/fn.TestRetryFuncNBackoffIncreases.func1
            /home/runner/work/go/pkg/mod/pgregory.net/rapid@v1.2.0/engine.go:371 in pgregory.net/rapid.checkOnce
        Failed test output:
    retry_test.go:117: [rapid] draw maxRetries: 2
    retry_test.go:119: [rapid] draw initialBackoffMs: 5
    retry_test.go:125: [rapid] draw backoffMultiplier: 2.345791173138418
    retry_test.go:127: [rapid] draw maxBackoffMs: 308
```

**Comment by Roasbeef** [comment]
Pushed up a version of the test that gives more tolerance for the assertions, but makes sure that the property is still upheld (backoff incrases).
